import { ThemePreset } from './index';

export const auroraVeilTheme: ThemePreset = {
    id: 'aurora-veil',
    name: 'Aurora Veil',
    description: 'Vidro fosco em lavanda pastel, com uma aurora suave no fundo — a contraparte inverte para uma noite de aurora profunda.',
    design: {
        matrixGap: 10,
        matrixRadius: 14,
        matrixItemBg: 'rgba(255, 255, 255, 0.6)',
        matrixBorderColor: 'rgba(155, 127, 196, 0.15)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.6)',
        matrixBlur: 12,
        animInstant: 100,
        animFast: 200,
        animNormal: 320,
        animSlow: 520,
        easeMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#f7f5fb',
        colorBgLayer1: '#ffffff',
        colorBgLayer2: '#efeaf7',
        bgBaseColor: '#f7f5fb',
        bgGradientMode: 'linear',
        bgGradientAngle: 160,
        surfaceMaterial: 'frosted',
        surfaceIntensity: 0.8,
        borderType: 'solid',
        systemTone: 'light',
        texture: 'aurora',
        textureOpacity: 0.12,
        atmosphereNoiseOpacity: 0,
        noiseIntensity: 0,
        bgNoiseDensity: 0,
        bgNoiseAnimation: 0,
        glassBlur: 16,
        glassOpacity: 0.6,
        glassSpecularity: 0.3,
        glassRoughness: 0.1,
        glassSaturation: 1.3,
        shadowIntensity: 0.4,
        layeredShadows: 1,
        shadowOrientation: 'bottom',
        shadowColorMode: 'neutral',
        shadowAmbientAlpha: 0.04,
        shadowProjectionBlur: 50,
        shadowProjectionAlpha: 0.06,
        securityShieldGlow: 0,
        securityPulseSpeed: 0,
        vignetteOpacity: 0,
        vignetteSoftness: 0,
        globalSaturation: 1,
        globalContrast: 1,
        contrastCurve: 1,
        identityAlignment: 'center',
        identityPadding: 16,
        identityFontFamily: '"Outfit", sans-serif',
        identityFontWeight: 600,
        identityTracking: 0,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 9999,
        btnRadiusTL: 9999,
        btnRadiusTR: 9999,
        btnRadiusBL: 9999,
        btnRadiusBR: 9999,
        btnHoverScale: 1.02,
        btnActiveScale: 0.98,
        btnPrimaryBg: 'rgba(155, 127, 196, 0.18)',
        btnPrimaryText: '#4a3a63',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.5)',
        btnGhostHoverBg: 'rgba(155, 127, 196, 0.1)',
        btnStyleType: 'frosted',
        btnNeonGlowColor: 'transparent',
        btnNeonPulseSpeed: 0,
        btnBackdropBlur: 16,
        cardActionBtnPrimaryBg: '#7a5fa8',
        cardActionBtnHoverBg: '#6a4f98',
        cardActionBtnText: '#ffffff',
        cardActionBtnBorderRadius: 9999,
        cardActionBtnPadding: 12,
        cardActionClickScale: 0.97,
        cardSearchBgFocus: 'rgba(255, 255, 255, 0.7)',
        cardSearchPlaceholderColor: '#8a7fa3',
        cardSearchTextFocusColor: '#3d2e52',
        cardTitleFontSize: 19,
        cardTitleColor: '#4a3a63',
        cardTitleFontWeight: '600',
        cardTitleLetterSpacing: 0,
        cardTitleIconGlow: 'transparent',
        cardBorderRadius: 28,
        cardRadiusTL: 28,
        cardRadiusTR: 28,
        cardRadiusBL: 28,
        cardRadiusBR: 28,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(255, 255, 255, 0.55)',
        cardBackdropBlur: 20,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 0,
        cardBorderColor: 'rgba(155, 127, 196, 0.15)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(255, 255, 255, 0.4)',
        cardInnerGlowWidth: 1,
        cardTextureType: 'none',
        cardTextureOpacity: 0,
        cardHeaderBg: 'rgba(255, 255, 255, 0.3)',
        cardHeaderBorder: 'rgba(155, 127, 196, 0.12)',
        cardHeaderPadding: 18,
        cardFooterBg: 'rgba(255, 255, 255, 0.3)',
        cardFooterBorder: 'rgba(155, 127, 196, 0.12)',
        cardShadowSpread: 20,
        cardGlowColor: 'rgba(155, 127, 196, 0.15)',
        cardGlowIntensity: 0.3,
        cardHoverTranslate: -6,
        cardHoverGlowIncrease: 0.2,
        cardSpotlightOpacity: 0.1,
        cardPaddingMd: 24,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.15,
        imageCardHoverZoom: 1.04,
        chatBubbleRadius: 20,
        chatUserBg: '#7a5fa8',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.15,
        colorPalette: 'default',
        primaryColor: '#9b7fc4',
        secondaryColor: '#7a5fa8',
        tertiaryColor: '#c8b8e0',
        accentColor: '#e0a5c8',
        surfaceColor: 'rgba(255, 255, 255, 0.5)',
        textureColor: '#c8b8e0',
        titleColor: '#3d2e52',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(247, 245, 251, 0.9)',
        chartColorPalette: '#9b7fc4',
        chartGridOpacity: 0.06,
        chartTooltipBg: '#ffffff',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: true,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 1000,
        zIndexToast: 2000,
        mode: 'light',
        navigationStyle: 'topbar',
        bodySize: '14px',
        inputBorderRadius: 9999,
        inputBg: 'rgba(255, 255, 255, 0.6)',
        inputBorderColor: 'rgba(155, 127, 196, 0.2)',
        inputFocusBorderColor: '#9b7fc4',
        inputTextColor: '#3d2e52',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 16,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: '',
        globalBackgroundBlur: 0,
        globalBackgroundOpacity: 1,
        motionEaseMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.1,
        motionDurationFast: 0.18,
        motionDurationNormal: 0.28,
        motionDurationSlow: 0.45,
        motionStaggerDelay: 0.05,
        isNavHidden: false,
        sidebarWidth: 260,
        sidebarMinWidth: 210,
        sidebarMaxWidth: 320,
        sidebarColor: 'rgba(255, 255, 255, 0.7)',
        sidebarHoverColor: 'rgba(155, 127, 196, 0.1)',
        sidebarActiveColor: 'rgba(155, 127, 196, 0.16)',
        sidebarNoiseOpacity: 0,
        topbarHeight: 68,
        topbarColor: 'rgba(255, 255, 255, 0.7)',
        topbarHoverColor: 'rgba(155, 127, 196, 0.1)',
        topbarActiveColor: 'rgba(155, 127, 196, 0.16)',
        topbarNoiseOpacity: 0,
        topbarTitleColor: '#4a3a63',
        tabGap: 8,
        tabSectionMargin: 16,
        navItemActiveColor: '#6a4f98',
        navActiveMarkerColor: '#9b7fc4',
        navActiveMarkerGlow: 0,
        sidebarBlur: 16,
        sidebarShadow: 'none',
        searchPositionTopbar: 'center',
        searchPositionSidebar: 'hidden',
        modalOverlayColor: 'rgba(247, 245, 251, 0.7)',
        modalOverlayBlur: 16,
        modalBorderRadius: 28,
        tooltipBg: '#3d2e52',
        tooltipTextColor: '#f7f5fb',
        tooltipRadius: 10,
        scrollWidth: 6,
        scrollRadius: 10,
        scrollTrackOpacity: 0.04,
        scrollThumbColor: '#c8b8e0',
        scrollThumbOpacity: 1,
        scrollThumbHoverOpacity: 1,
        scrollPadding: 2,
        aiPanelBg: 'rgba(255, 255, 255, 0.6)',
        aiGlowColor: '#9b7fc4',
        flowNodeRadius: 20,
        flowGridStyle: 'dots',
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#3b82f6',
        badgeRadius: 9999,
        switchTrackActiveBg: '#9b7fc4',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#9b7fc4',
        switchStyleType: 'tactile',
        switchBackdropBlur: 8,
        switchPulseColor: 'rgba(155, 127, 196, 0.4)',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1440px',
        layoutPadding: 32,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 28,
        borderRadiusSm: 10,
        borderRadiusMd: 16,
        borderRadiusLg: 36,
        borderWidth: 0,
        borderStyle: 'solid',
        layoutGap: 24,
        layoutGapSm: 12,
        layoutGapMd: 24,
        layoutGapLg: 40,
        iconFamily: 'lucide',
        iconWeight: 'regular',
        iconStrokeWidth: 1.5,
        scrollbarWidth: 6,
        scrollbarThumbColor: '#c8b8e0',
        industrialRegistry: false,
        tableHeaderBg: 'rgba(255, 255, 255, 0.4)',
        tableRowHoverBg: 'rgba(155, 127, 196, 0.06)',
        tableCellPadding: 16,
        tableBorderColor: 'rgba(155, 127, 196, 0.12)',
        headingFont: '"Outfit", sans-serif',
        bodyFont: '"Inter", sans-serif',
        monoFont: '"JetBrains Mono", monospace',
        textColorMaster: '#3d2e52',
        textColorSecondary: '#6a5a80',
        textColorMuted: '#665879',
        h1Size: 34,
        h1Weight: '700',
        h1LineHeight: 1.2,
        h1LetterSpacing: -0.5,
        h2Size: 26,
        h2Weight: '600',
        h2LineHeight: 1.3,
        bodyLineHeight: 1.7,
        bodyWeight: '400',
        headingTransform: 'none',
        textSmoothing: true,
        textGlowIntensity: 0,
        enabledLanguages: ['pt', 'en', 'es', 'fr', 'de', 'it'],
    },
    contraparte: {
        mode: 'dark',
        bgBaseColor: '#14101f',
        colorBgBody: '#14101f',
        colorBgLayer1: '#1c1729',
        colorBgLayer2: '#241d34',
        sidebarColor: 'rgba(28, 23, 41, 0.7)',
        sidebarHoverColor: 'rgba(200, 184, 224, 0.1)',
        sidebarActiveColor: 'rgba(200, 184, 224, 0.16)',
        topbarColor: 'rgba(28, 23, 41, 0.7)',
        topbarHoverColor: 'rgba(200, 184, 224, 0.1)',
        topbarActiveColor: 'rgba(200, 184, 224, 0.16)',
        topbarTitleColor: '#e5dcf5',
        cardBackgroundColor: 'rgba(36, 29, 52, 0.6)',
        cardBorderColor: 'rgba(200, 184, 224, 0.15)',
        cardHeaderBg: 'rgba(255, 255, 255, 0.03)',
        cardHeaderBorder: 'rgba(200, 184, 224, 0.1)',
        cardFooterBg: 'rgba(255, 255, 255, 0.03)',
        cardFooterBorder: 'rgba(200, 184, 224, 0.1)',
        cardTitleColor: '#e5dcf5',
        cardActionBtnPrimaryBg: '#c8b8e0',
        cardActionBtnHoverBg: '#b8a6d8',
        cardActionBtnText: '#1c1729',
        cardSearchBgFocus: 'rgba(255, 255, 255, 0.05)',
        cardSearchPlaceholderColor: '#8d80a3',
        cardSearchTextFocusColor: '#f2ecfa',
        modalOverlayColor: 'rgba(0, 0, 0, 0.5)',
        colorBgModal: '#14101f',
        tooltipBg: '#c8b8e0',
        tooltipTextColor: '#1c1729',
        tableHeaderBg: 'rgba(255, 255, 255, 0.03)',
        tableRowHoverBg: 'rgba(255, 255, 255, 0.02)',
        tableBorderColor: 'rgba(200, 184, 224, 0.12)',
        textColorMaster: '#f2ecfa',
        textColorSecondary: '#c3b6d6',
        textColorMuted: '#9d90b3',
        btnPrimaryBg: 'rgba(200, 184, 224, 0.14)',
        btnPrimaryText: '#e5dcf5',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.06)',
        inputBg: 'rgba(28, 23, 41, 0.6)',
        inputBorderColor: 'rgba(200, 184, 224, 0.18)',
        inputFocusBorderColor: '#c8b8e0',
        inputTextColor: '#f2ecfa',
        surfaceColor: 'rgba(36, 29, 52, 0.5)',
        textureColor: '#4a3f63',
        titleColor: '#f2ecfa',
        chartTooltipBg: 'rgba(36, 29, 52, 0.9)',
        scrollThumbColor: '#4a3f63',
        aiPanelBg: 'rgba(28, 23, 41, 0.6)',
        matrixItemBg: 'rgba(255, 255, 255, 0.04)',
        matrixBorderColor: 'rgba(200, 184, 224, 0.14)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.04)',
        navItemActiveColor: '#e5dcf5',
        navActiveMarkerColor: '#c8b8e0',
    }
};
