import { ThemePreset } from './index';

export const blueprintProtocolTheme: ThemePreset = {
    id: 'blueprint-protocol',
    name: 'Blueprint Protocol',
    description: 'Esquemático de engenharia: grade cianotipo, sidebar flutuante e botão wireframe angular — a contraparte inverte para o papel de blueprint.',
    design: {
        matrixGap: 10,
        matrixRadius: 2,
        matrixItemBg: 'rgba(255, 255, 255, 0.03)',
        matrixBorderColor: 'rgba(122, 168, 213, 0.2)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.04)',
        matrixBlur: 0,
        animInstant: 80,
        animFast: 150,
        animNormal: 250,
        animSlow: 400,
        easeMain: 'cubic-bezier(0.16, 1, 0.3, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#33445d',
        colorBgLayer1: '#2a3850',
        colorBgLayer2: '#212c42',
        bgBaseColor: '#33445d',
        bgGradientMode: 'none',
        bgGradientAngle: 0,
        surfaceMaterial: 'industrial',
        surfaceIntensity: 0.9,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'blueprint-pro',
        textureOpacity: 0.16,
        atmosphereNoiseOpacity: 0,
        noiseIntensity: 0,
        bgNoiseDensity: 0,
        bgNoiseAnimation: 0,
        glassBlur: 0,
        glassOpacity: 1,
        glassSpecularity: 0,
        glassRoughness: 1,
        glassSaturation: 1,
        shadowIntensity: 0.4,
        layeredShadows: 1,
        shadowOrientation: 'bottom',
        shadowColorMode: 'colored',
        shadowAmbientAlpha: 0.3,
        shadowProjectionBlur: 30,
        shadowProjectionAlpha: 0.3,
        securityShieldGlow: 8,
        securityPulseSpeed: 1.5,
        vignetteOpacity: 0.15,
        vignetteSoftness: 60,
        globalSaturation: 1,
        globalContrast: 1.1,
        contrastCurve: 1,
        identityAlignment: 'left',
        identityPadding: 16,
        identityFontFamily: '"JetBrains Mono", monospace',
        identityFontWeight: 700,
        identityTracking: 1,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 0,
        btnRadiusTL: 0,
        btnRadiusTR: 6,
        btnRadiusBL: 0,
        btnRadiusBR: 6,
        btnHoverScale: 1,
        btnActiveScale: 0.97,
        btnPrimaryBg: 'transparent',
        btnPrimaryText: '#7ad4ff',
        btnSecondaryBg: 'rgba(122, 168, 213, 0.08)',
        btnGhostHoverBg: 'rgba(122, 168, 213, 0.12)',
        btnStyleType: 'cyberpunk',
        btnNeonGlowColor: 'rgba(122, 212, 255, 0.5)',
        btnNeonPulseSpeed: 1.2,
        btnBackdropBlur: 0,
        cardActionBtnPrimaryBg: '#3a6690',
        cardActionBtnHoverBg: '#2d5171',
        cardActionBtnText: '#e5f1fb',
        cardActionBtnBorderRadius: 0,
        cardActionBtnPadding: 12,
        cardActionClickScale: 0.96,
        cardSearchBgFocus: 'rgba(122, 168, 213, 0.1)',
        cardSearchPlaceholderColor: 'rgba(210, 228, 245, 0.4)',
        cardSearchTextFocusColor: '#e5f1fb',
        cardTitleFontSize: 18,
        cardTitleColor: '#7ad4ff',
        cardTitleFontWeight: '700',
        cardTitleLetterSpacing: 1,
        cardTitleIconGlow: 'rgba(122, 212, 255, 0.3)',
        cardBorderRadius: 2,
        cardRadiusTL: 2,
        cardRadiusTR: 2,
        cardRadiusBL: 2,
        cardRadiusBR: 2,
        cardGeometricCut: 12,
        cardBackgroundColor: 'rgba(20, 28, 42, 0.7)',
        cardBackdropBlur: 0,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 2,
        cardBorderColor: 'rgba(122, 168, 213, 0.4)',
        cardBorderOpacity: 1,
        cardBorderTop: 2,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(122, 212, 255, 0.08)',
        cardInnerGlowWidth: 1,
        cardTextureType: 'grid',
        cardTextureOpacity: 0.15,
        cardHeaderBg: 'rgba(122, 168, 213, 0.08)',
        cardHeaderBorder: 'rgba(122, 168, 213, 0.3)',
        cardHeaderPadding: 14,
        cardFooterBg: 'rgba(20, 28, 42, 0.4)',
        cardFooterBorder: 'rgba(122, 168, 213, 0.2)',
        cardShadowSpread: 0,
        cardGlowColor: 'rgba(122, 212, 255, 0.15)',
        cardGlowIntensity: 0.3,
        cardHoverTranslate: -2,
        cardHoverGlowIncrease: 0.3,
        cardSpotlightOpacity: 0.1,
        cardPaddingMd: 20,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.3,
        imageCardHoverZoom: 1.02,
        chatBubbleRadius: 4,
        chatUserBg: '#4a7fb5',
        chatBubbleStyle: 'solid',
        chatAnimationSpeed: 0.1,
        colorPalette: 'default',
        primaryColor: '#4a7fb5',
        secondaryColor: '#7ad4ff',
        tertiaryColor: '#2a3850',
        accentColor: '#a8d8ff',
        surfaceColor: '#2a3850',
        textureColor: '#7aa8d5',
        titleColor: '#e5f1fb',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(33, 44, 66, 0.95)',
        chartColorPalette: '#4a7fb5',
        chartGridOpacity: 0.15,
        chartTooltipBg: '#212c42',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: false,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 2000,
        zIndexToast: 2000,
        mode: 'dark',
        navigationStyle: 'sidebar',
        sidebarPosition: 'floating',
        bodySize: '14px',
        inputBorderRadius: 0,
        inputBg: 'rgba(20, 28, 42, 0.6)',
        inputBorderColor: 'rgba(122, 168, 213, 0.3)',
        inputFocusBorderColor: '#7ad4ff',
        inputTextColor: '#e5f1fb',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 0,
        layerBackdropOpacity: 0.5,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: '',
        globalBackgroundBlur: 0,
        globalBackgroundOpacity: 1,
        motionEaseMain: 'cubic-bezier(0.2, 0, 0, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.08,
        motionDurationFast: 0.15,
        motionDurationNormal: 0.22,
        motionDurationSlow: 0.35,
        motionStaggerDelay: 0.03,
        isNavHidden: false,
        sidebarWidth: 240,
        sidebarMinWidth: 200,
        sidebarMaxWidth: 320,
        sidebarColor: 'rgba(20, 28, 42, 0.85)',
        sidebarHoverColor: 'rgba(122, 212, 255, 0.1)',
        sidebarActiveColor: 'rgba(122, 212, 255, 0.16)',
        sidebarNoiseOpacity: 0,
        topbarHeight: 56,
        topbarColor: 'rgba(20, 28, 42, 0.85)',
        topbarHoverColor: 'rgba(122, 212, 255, 0.1)',
        topbarActiveColor: 'rgba(122, 212, 255, 0.16)',
        topbarNoiseOpacity: 0,
        topbarTitleColor: '#7ad4ff',
        tabGap: 6,
        tabSectionMargin: 12,
        navItemActiveColor: '#7ad4ff',
        navActiveMarkerColor: '#7ad4ff',
        navActiveMarkerGlow: 8,
        sidebarBlur: 4,
        sidebarShadow: '0 0 24px rgba(0,0,0,0.4)',
        searchPositionTopbar: 'left',
        searchPositionSidebar: 'top',
        modalOverlayColor: 'rgba(10, 20, 32, 0.8)',
        modalOverlayBlur: 4,
        modalBorderRadius: 2,
        tooltipBg: '#0a1420',
        tooltipTextColor: '#7ad4ff',
        tooltipRadius: 0,
        scrollWidth: 6,
        scrollRadius: 0,
        scrollTrackOpacity: 0.1,
        scrollThumbColor: '#4a7fb5',
        scrollThumbOpacity: 1,
        scrollThumbHoverOpacity: 1,
        scrollPadding: 2,
        aiPanelBg: 'rgba(20, 28, 42, 0.85)',
        aiGlowColor: '#7ad4ff',
        flowNodeRadius: 0,
        flowGridStyle: 'lines',
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#3b82f6',
        badgeRadius: 0,
        switchTrackActiveBg: '#4a7fb5',
        switchThumbBg: '#e5f1fb',
        checkboxActiveColor: '#4a7fb5',
        switchStyleType: 'tactile',
        switchBackdropBlur: 0,
        switchPulseColor: 'rgba(122, 212, 255, 0.4)',
        layout: 'grid',
        layoutDensity: 'compact',
        maxContentWidth: '1440px',
        layoutPadding: 20,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 2,
        borderRadiusSm: 0,
        borderRadiusMd: 2,
        borderRadiusLg: 6,
        borderWidth: 2,
        borderStyle: 'solid',
        layoutGap: 16,
        layoutGapSm: 8,
        layoutGapMd: 16,
        layoutGapLg: 24,
        iconFamily: 'tabler',
        iconWeight: 'regular',
        iconStrokeWidth: 1.75,
        scrollbarWidth: 6,
        scrollbarThumbColor: '#4a7fb5',
        industrialRegistry: true,
        tableHeaderBg: 'rgba(122, 168, 213, 0.08)',
        tableRowHoverBg: 'rgba(122, 168, 213, 0.05)',
        tableCellPadding: 12,
        tableBorderColor: 'rgba(122, 168, 213, 0.2)',
        headingFont: '"JetBrains Mono", monospace',
        bodyFont: '"Inter", sans-serif',
        monoFont: '"JetBrains Mono", monospace',
        textColorMaster: '#e5f1fb',
        textColorSecondary: '#a8c3dc',
        textColorMuted: '#9bb4c9',
        h1Size: 28,
        h1Weight: '700',
        h1LineHeight: 1.2,
        h1LetterSpacing: 0,
        h2Size: 20,
        h2Weight: '700',
        h2LineHeight: 1.3,
        bodyLineHeight: 1.6,
        bodyWeight: '400',
        headingTransform: 'uppercase',
        textSmoothing: true,
        textGlowIntensity: 0.2,
        enabledLanguages: ['pt', 'en', 'es', 'fr', 'de', 'it'],
    },
    contraparte: {
        mode: 'light',
        bgBaseColor: '#eef4fb',
        colorBgBody: '#eef4fb',
        colorBgLayer1: '#ffffff',
        colorBgLayer2: '#e2ecf7',
        sidebarColor: 'rgba(255, 255, 255, 0.9)',
        sidebarHoverColor: 'rgba(74, 127, 181, 0.08)',
        sidebarActiveColor: 'rgba(74, 127, 181, 0.14)',
        topbarColor: 'rgba(255, 255, 255, 0.9)',
        topbarHoverColor: 'rgba(74, 127, 181, 0.08)',
        topbarActiveColor: 'rgba(74, 127, 181, 0.14)',
        topbarTitleColor: '#1c3a5c',
        cardBackgroundColor: '#ffffff',
        cardBorderColor: '#b8d0e8',
        cardHeaderBg: '#e2ecf7',
        cardHeaderBorder: '#b8d0e8',
        cardFooterBg: '#e2ecf7',
        cardFooterBorder: '#b8d0e8',
        cardTitleColor: '#1c3a5c',
        cardActionBtnPrimaryBg: '#2f5f8f',
        cardActionBtnHoverBg: '#254c72',
        cardActionBtnText: '#ffffff',
        cardSearchBgFocus: '#e2ecf7',
        cardSearchPlaceholderColor: '#5c7791',
        cardSearchTextFocusColor: '#16283d',
        modalOverlayColor: 'rgba(238, 244, 251, 0.85)',
        colorBgModal: '#eef4fb',
        tooltipBg: '#1c3a5c',
        tooltipTextColor: '#eef4fb',
        tableHeaderBg: '#e2ecf7',
        tableRowHoverBg: '#d8e6f4',
        tableBorderColor: '#b8d0e8',
        textColorMaster: '#16283d',
        textColorSecondary: '#3d5a78',
        textColorMuted: '#4a6178',
        btnPrimaryText: '#2f5f8f',
        btnSecondaryBg: '#e2ecf7',
        btnGhostHoverBg: '#d8e6f4',
        inputBg: '#ffffff',
        inputBorderColor: '#b8d0e8',
        inputFocusBorderColor: '#2f5f8f',
        inputTextColor: '#16283d',
        surfaceColor: '#e2ecf7',
        textureColor: '#b8d0e8',
        titleColor: '#16283d',
        chartTooltipBg: '#e2ecf7',
        scrollThumbColor: '#b8d0e8',
        aiPanelBg: '#ffffff',
        matrixItemBg: '#e2ecf7',
        matrixBorderColor: '#b8d0e8',
        matrixSearchBg: '#ffffff',
        navItemActiveColor: '#2f5f8f',
        navActiveMarkerColor: '#2f5f8f',
    }
};
