import { ThemePreset } from './index';

/**
 * Tema Gerado Automaticamente pela Skill Sarak-UI-criar-tema
 * 
 * Siga as instruções do workflow para preencher as variáveis abaixo.
 * NUNCA adicione propriedades que não estejam mapeadas no schema oficial.
 */
export const cyberRetroWaveTheme: ThemePreset = {
    id: 'cyber-retro-wave',
    name: 'Cyber Retro-Wave 2077',
    description: 'Uma imersão visual no estilo neon cyberpunk e retrowave dos anos 80, com alto contraste, cortes geométricos e brilho intenso.',
    design: {
        tooltipTextColor: '#6280c7',
        matrixGap: 12,
        matrixRadius: 12,
        matrixItemBg: 'rgba(255, 255, 255, 0.02)',
        matrixBorderColor: 'rgba(255, 255, 255, 0.05)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.05)',
        matrixBlur: 10,
        animInstant: 100,
        animFast: 200,
        animNormal: 300,
        animSlow: 500,
        easeMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#05030a',
        colorBgLayer1: '#0a0514',
        colorBgLayer2: '#140a28',
        bgBaseColor: '#080411',
        bgGradientMode: 'linear',
        bgGradientAngle: 135,
        surfaceMaterial: 'frosted',
        surfaceIntensity: 0.5,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'scanlines',
        textureOpacity: 0.3,
        atmosphereNoiseOpacity: 0.05,
        noiseIntensity: 0.05,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 1,
        glassBlur: 16,
        glassOpacity: 0.1,
        glassSpecularity: 0.1,
        glassRoughness: 0.05,
        glassSaturation: 1.2,
        shadowIntensity: 0.5,
        layeredShadows: 1,
        shadowOrientation: 'bottom',
        shadowColorMode: 'neutral',
        shadowAmbientAlpha: 0.4,
        shadowProjectionBlur: 40,
        shadowProjectionAlpha: 0.2,
        securityShieldGlow: 10,
        securityPulseSpeed: 2,
        vignetteOpacity: 0.3,
        vignetteSoftness: 50,
        globalSaturation: 1,
        globalContrast: 1,
        contrastCurve: 1,
        identityAlignment: 'left',
        identityPadding: 16,
        identityFontFamily: 'Inter',
        identityFontWeight: 700,
        identityTracking: 0,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 0,
        btnRadiusTL: 0,
        btnRadiusTR: 0,
        btnRadiusBL: 0,
        btnRadiusBR: 0,
        btnHoverScale: 1.05,
        btnActiveScale: 0.95,
        btnPrimaryBg: '#ff00ff',
        btnPrimaryText: '#000000',
        btnSecondaryBg: 'rgba(0, 255, 255, 0.1)',
        btnGhostHoverBg: 'rgba(255, 0, 255, 0.2)',
        btnStyleType: 'neon',
        btnNeonGlowColor: 'rgba(255, 0, 255, 0.6)',
        btnNeonPulseSpeed: 2.0,
        btnBackdropBlur: 10,
        cardActionBtnPrimaryBg: '#00f2ff',
        cardActionBtnHoverBg: 'rgba(0, 242, 255, 0.8)',
        cardActionBtnText: '#090d16',
        cardActionBtnBorderRadius: 8,
        cardActionBtnPadding: 12,
        cardActionClickScale: 0.96,
        cardSearchBgFocus: 'rgba(0, 242, 255, 0.08)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.4)',
        cardSearchTextFocusColor: '#ffffff',
        cardTitleFontSize: 20,
        cardTitleColor: '#ffffff',
        cardTitleFontWeight: '900',
        cardTitleLetterSpacing: 0,
        cardTitleIconGlow: 'rgba(0, 242, 255, 0.2)',
        cardBorderRadius: 0,
        cardRadiusTL: 0,
        cardRadiusTR: 0,
        cardRadiusBL: 0,
        cardRadiusBR: 0,
        cardGeometricCut: 24,
        cardBackgroundColor: 'rgba(10, 5, 20, 0.8)',
        cardBackdropBlur: 16,
        cardSurfaceOpacity: 0.9,
        cardBorderWidth: 2,
        cardBorderColor: '#00ffff',
        cardBorderOpacity: 1,
        cardBorderTop: 2,
        cardBorderBottom: 2,
        cardBorderLeft: 2,
        cardBorderRight: 2,
        cardInnerGlowColor: 'rgba(255, 255, 255, 0.05)',
        cardInnerGlowWidth: 1,
        cardTextureType: 'none',
        cardTextureOpacity: 0.03,
        cardHeaderBg: 'rgba(255, 255, 255, 0.03)',
        cardHeaderBorder: 'rgba(255, 255, 255, 0.05)',
        cardHeaderPadding: 16,
        cardFooterBg: 'transparent',
        cardFooterBorder: 'rgba(255, 255, 255, 0.05)',
        cardShadowSpread: 20,
        cardGlowColor: 'rgba(0, 242, 255, 0.05)',
        cardGlowIntensity: 0,
        cardHoverTranslate: -4,
        cardHoverGlowIncrease: 0.2,
        cardSpotlightOpacity: 0.1,
        cardPaddingMd: 24,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.5,
        imageCardHoverZoom: 1.05,
        chatBubbleRadius: 12,
        chatUserBg: 'rgba(255, 255, 255, 0.05)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.05,
        colorPalette: 'neon',
        primaryColor: '#ff00ff',
        secondaryColor: '#00ffff',
        tertiaryColor: '#ffaa00',
        accentColor: '#ff0055',
        surfaceColor: '#0f0b1a',
        textureColor: '#ff00ff',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(15, 15, 15, 0.8)',
        chartColorPalette: '#00f2ff',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(15, 23, 42, 0.9)',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: true,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 2000,
        zIndexToast: 2000,
        mode: 'dark',
        navigationStyle: 'sidebar',
        bodySize: '14px',
        inputBorderRadius: 8,
        inputBg: 'rgba(255, 255, 255, 0.03)',
        inputBorderColor: 'rgba(255, 255, 255, 0.1)',
        inputFocusBorderColor: '#00f2ff',
        inputTextColor: '#ffffff',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 10,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: '',
        globalBackgroundBlur: 0,
        globalBackgroundBlendMode: 'normal',
        globalBackgroundOpacity: 1,
        motionEaseMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.1,
        motionDurationFast: 0.2,
        motionDurationNormal: 0.3,
        motionDurationSlow: 0.6,
        motionStaggerDelay: 0.05,
        isNavHidden: false,
        sidebarWidth: 240,
        sidebarMinWidth: 200,
        sidebarMaxWidth: 450,
        sidebarColor: '#000000',
        sidebarHoverColor: 'transparent',
        sidebarActiveColor: 'transparent',
        sidebarNoiseOpacity: 0,
        topbarHeight: 64,
        topbarColor: '#000000',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0,
        topbarTitleColor: '#ffffff',
        tabGap: 8,
        tabSectionMargin: 16,
        navItemActiveColor: '#00f2ff',
        navActiveMarkerColor: '#00f2ff',
        navActiveMarkerGlow: 10,
        sidebarBlur: 10,
        sidebarShadow: '10px 0 30px rgba(0,0,0,0.5)',
        searchPositionTopbar: 'left',
        searchPositionSidebar: 'top',
        modalOverlayColor: 'rgba(0, 0, 0, 0.4)',
        modalOverlayBlur: 8,
        modalBorderRadius: 16,
        tooltipBg: '#0f172a',
        tooltipRadius: 4,
        scrollWidth: 6,
        scrollRadius: 10,
        scrollTrackOpacity: 0.05,
        scrollThumbColor: '#ffffff',
        scrollThumbOpacity: 0.2,
        scrollThumbHoverOpacity: 0.5,
        scrollPadding: 2,
        aiPanelBg: 'rgba(0, 0, 0, 0.4)',
        aiGlowColor: '#00f2ff',
        flowNodeRadius: 12,
        flowGridStyle: 'dots',
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#3b82f6',
        badgeRadius: 99,
        switchTrackActiveBg: '#00f2ff',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#00f2ff',
        switchStyleType: 'tactile',
        switchBackdropBlur: 4,
        switchPulseColor: '#00f2ff',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1440px',
        layoutPadding: 32,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 12,
        borderRadiusSm: 6,
        borderRadiusMd: 12,
        borderRadiusLg: 20,
        borderWidth: 1,
        borderStyle: 'solid',
        layoutGap: 24,
        layoutGapSm: 12,
        layoutGapMd: 24,
        layoutGapLg: 36,
        iconFamily: 'lucide',
        iconWeight: 'regular',
        iconStrokeWidth: 2,
        scrollbarWidth: 6,
        scrollbarThumbColor: 'rgba(255, 255, 255, 0.1)',
        industrialRegistry: true,
        tableHeaderBg: 'rgba(255, 255, 255, 0.03)',
        tableRowHoverBg: 'rgba(255, 255, 255, 0.02)',
        tableCellPadding: 12,
        tableBorderColor: 'rgba(255, 255, 255, 0.05)',
        headingFont: '\'Orbitron\', sans-serif',
        bodyFont: '\'Chakra Petch\', sans-serif',
        monoFont: '\'VT323\', monospace',
        textColorMaster: '#ffffff',
        textColorSecondary: 'rgba(255, 255, 255, 0.7)',
        textColorMuted: '#ffffff77',
        h1Size: 48,
        h1Weight: '900',
        h1LineHeight: 1.1,
        h1LetterSpacing: -1,
        h2Size: 32,
        h2Weight: '700',
        h2LineHeight: 1.2,
        bodyLineHeight: 1.6,
        bodyWeight: '400',
        headingTransform: 'uppercase',
        textSmoothing: false,
        textGlowIntensity: 0.8
    }
};
