import { ThemePreset } from './index';

/**
 * Tema Gerado Automaticamente pela Skill Sarak-UI-criar-tema
 * 
 * Siga as instruções do workflow para preencher as variáveis abaixo.
 * NUNCA adicione propriedades que não estejam mapeadas no schema oficial.
 */
export const dotMatrixElegantTheme: ThemePreset = {
    id: 'dot-matrix-elegant',
    name: 'Dot Matrix Elegant',
    description: 'Um tema sofisticado, escuro com fundo pontilhado e detalhes em dourado metálico.',
    design: {
        matrixGap: 12,
        matrixRadius: 12,
        matrixItemBg: 'rgba(255, 255, 255, 0.02)',
        matrixBorderColor: 'rgba(255, 255, 255, 0.05)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.05)',
        matrixBlur: 10,
        animInstant: 100,
        animFast: 200,
        animNormal: 300,
        animSlow: 500,
        easeMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#050505',
        colorBgLayer1: '#090909',
        colorBgLayer2: '#121212',
        bgBaseColor: '#050505',
        bgGradientMode: 'linear',
        bgGradientAngle: 135,
        surfaceMaterial: 'frosted',
        surfaceIntensity: 0.5,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'dots',
        textureOpacity: 0.15,
        atmosphereNoiseOpacity: 0.05,
        noiseIntensity: 0.05,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 1,
        glassBlur: 16,
        glassOpacity: 0.1,
        glassSpecularity: 0.1,
        glassRoughness: 0.05,
        glassSaturation: 1.2,
        shadowIntensity: 0.5,
        layeredShadows: 1,
        shadowOrientation: 'bottom',
        shadowColorMode: 'neutral',
        shadowAmbientAlpha: 0.4,
        shadowProjectionBlur: 40,
        shadowProjectionAlpha: 0.2,
        securityShieldGlow: 10,
        securityPulseSpeed: 2,
        vignetteOpacity: 0.3,
        vignetteSoftness: 50,
        globalSaturation: 1,
        globalContrast: 1,
        contrastCurve: 1,
        identityAlignment: 'left',
        identityPadding: 16,
        identityFontFamily: 'Outfit',
        identityFontWeight: 700,
        identityTracking: 0,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 8,
        btnRadiusTL: 8,
        btnRadiusTR: 8,
        btnRadiusBL: 8,
        btnRadiusBR: 8,
        btnHoverScale: 1.02,
        btnActiveScale: 0.98,
        btnPrimaryBg: '#00f2ff',
        btnPrimaryText: '#000000',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.05)',
        btnStyleType: 'matte',
        btnNeonGlowColor: 'rgba(0, 242, 255, 0.4)',
        btnNeonPulseSpeed: 1.5,
        btnBackdropBlur: 8,
        cardActionBtnPrimaryBg: '#d4af37',
        cardActionBtnHoverBg: 'rgba(212, 175, 55, 0.8)',
        cardActionBtnText: '#000000',
        cardActionBtnBorderRadius: 4,
        cardActionBtnPadding: 14,
        cardActionClickScale: 0.95,
        cardSearchBgFocus: 'rgba(212, 175, 55, 0.05)',
        cardSearchBorderBeamActive: false,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.2)',
        cardSearchTextFocusColor: '#d4af37',
        cardTitleFontSize: 22,
        cardTitleColor: '#d4af37',
        cardTitleFontWeight: '400',
        cardTitleLetterSpacing: 3,
        cardTitleIconGlow: 'transparent',
        cardBorderRadius: 4,
        cardRadiusTL: 4,
        cardRadiusTR: 4,
        cardRadiusBL: 4,
        cardRadiusBR: 4,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(10, 10, 10, 0.9)',
        cardBackdropBlur: 8,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 1,
        cardBorderColor: 'rgba(212, 175, 55, 0.1)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'transparent',
        cardInnerGlowWidth: 0,
        cardTextureType: 'dots',
        cardTextureOpacity: 0.02,
        cardHeaderBg: 'transparent',
        cardHeaderBorder: 'rgba(212, 175, 55, 0.1)',
        cardHeaderPadding: 24,
        cardFooterBg: 'transparent',
        cardFooterBorder: 'rgba(212, 175, 55, 0.1)',
        cardShadowSpread: 10,
        cardGlowColor: 'transparent',
        cardGlowIntensity: 0,
        cardHoverTranslate: -1,
        cardHoverGlowIncrease: 0,
        cardSpotlightOpacity: 0.05,
        cardPaddingMd: 32,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.5,
        imageCardHoverZoom: 1.05,
        chatBubbleRadius: 12,
        chatUserBg: 'rgba(255, 255, 255, 0.05)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.05,
        colorPalette: 'default',
        primaryColor: '#d4af37',
        secondaryColor: '#a67c00',
        tertiaryColor: '#f3e5ab',
        accentColor: '#ffffff',
        surfaceColor: '#121212',
        textureColor: '#d4af37',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(15, 15, 15, 0.8)',
        chartColorPalette: '#00f2ff',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(15, 23, 42, 0.9)',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: true,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 2000,
        zIndexToast: 2000,
        mode: 'dark',
        navigationStyle: 'sidebar',
        bodySize: '14px',
        inputBorderRadius: 8,
        inputBg: 'rgba(255, 255, 255, 0.03)',
        inputBorderColor: 'rgba(255, 255, 255, 0.1)',
        inputFocusBorderColor: '#00f2ff',
        inputTextColor: '#ffffff',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 10,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: '',
        globalBackgroundBlur: 0,
        globalBackgroundBlendMode: 'normal',
        globalBackgroundOpacity: 1,
        motionEaseMain: 'cubic-bezier(0.25, 1, 0.5, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.2,
        motionDurationFast: 0.4,
        motionDurationNormal: 0.6,
        motionDurationSlow: 1.0,
        motionStaggerDelay: 0.1,
        isNavHidden: false,
        sidebarWidth: 260,
        sidebarMinWidth: 220,
        sidebarMaxWidth: 350,
        sidebarColor: '#050505',
        sidebarHoverColor: '#0a0a0a',
        sidebarActiveColor: '#0d0d0d',
        sidebarNoiseOpacity: 0.02,
        topbarHeight: 72,
        topbarColor: '#050505',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0.02,
        topbarTitleColor: '#d4af37',
        tabGap: 24,
        tabSectionMargin: 32,
        navItemActiveColor: '#d4af37',
        navActiveMarkerColor: '#d4af37',
        navActiveMarkerGlow: 0,
        sidebarBlur: 0,
        sidebarShadow: '1px 0 0 rgba(212, 175, 55, 0.1)',
        searchPositionTopbar: 'right',
        searchPositionSidebar: 'hidden',
        modalOverlayColor: 'rgba(0, 0, 0, 0.9)',
        modalOverlayBlur: 4,
        modalBorderRadius: 4,
        tooltipBg: '#1a1a1a',
        tooltipRadius: 2,
        scrollWidth: 4,
        scrollRadius: 0,
        scrollTrackOpacity: 0.02,
        scrollThumbColor: '#d4af37',
        scrollThumbOpacity: 0.3,
        scrollThumbHoverOpacity: 0.6,
        scrollPadding: 2,
        aiPanelBg: '#080808',
        aiGlowColor: 'transparent',
        flowNodeRadius: 4,
        flowGridStyle: 'dots',
        statusSuccessColor: '#a67c00',
        statusErrorColor: '#8a0303',
        statusWarningColor: '#d4af37',
        statusInfoColor: '#c0c0c0',
        badgeRadius: 2,
        switchTrackActiveBg: '#d4af37',
        switchThumbBg: '#050505',
        checkboxActiveColor: '#d4af37',
        switchStyleType: 'tactile',
        switchBackdropBlur: 0,
        switchPulseColor: 'transparent',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1000px',
        layoutPadding: 64,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 4,
        borderRadiusSm: 2,
        borderRadiusMd: 4,
        borderRadiusLg: 8,
        borderWidth: 1,
        borderStyle: 'solid',
        layoutGap: 48,
        layoutGapSm: 24,
        layoutGapMd: 48,
        layoutGapLg: 64,
        iconFamily: 'lucide',
        iconWeight: 'light',
        iconStrokeWidth: 1,
        scrollbarWidth: 4,
        scrollbarThumbColor: 'rgba(212, 175, 55, 0.2)',
        industrialRegistry: false,
        tableHeaderBg: 'transparent',
        tableRowHoverBg: 'rgba(212, 175, 55, 0.02)',
        tableCellPadding: 24,
        tableBorderColor: 'rgba(212, 175, 55, 0.1)',
        headingFont: '\'Outfit\', sans-serif',
        bodyFont: '\'Outfit\', sans-serif',
        monoFont: '\'JetBrains Mono\', monospace',
        textColorMaster: '#d4af37',
        textColorSecondary: '#a67c00',
        textColorMuted: '#595959',
        h1Size: 52,
        h1Weight: '300',
        h1LineHeight: 1.2,
        h1LetterSpacing: 2,
        h2Size: 36,
        h2Weight: '300',
        h2LineHeight: 1.3,
        bodyLineHeight: 1.8,
        bodyWeight: '300',
        headingTransform: 'none',
        textSmoothing: true,
        textGlowIntensity: 0
    }
};
