import { ThemePreset } from './index';

export const holographicGlassTheme: ThemePreset = {
    id: 'holographic-glass',
    name: 'Holographic Glass',
    description: 'Sci-fi holographic interface. Extreme glassmorphism, thin translucent borders, massive blurs, and neon magenta/blue accents over a deep abyss.',
    design: {
        mode: 'dark',
        navigationStyle: 'topbar',
        bodySize: '15px',
        systemName: 'Holo OS',
        logoUrl: '',
        logoMinimalUrl: '',
        logoScale: 100,
        identityAlignment: 'center',
        identityPadding: 16,
        identityFontFamily: 'Inter',
        identityFontWeight: 300,
        identityTracking: 2,
        identityRedirectUrl: '/',
        identityHoverEffect: 'glow',
        bgBaseColor: '#030514',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1440px',
        layoutPadding: 32,
        isSplitViewEnabled: true,
        isAutoHideEnabled: true,
        borderRadius: 24,
        borderRadiusSm: 12,
        borderRadiusMd: 24,
        borderRadiusLg: 36,
        borderWidth: 1,
        borderStyle: 'solid',
        layoutGap: 32,
        layoutGapSm: 16,
        layoutGapMd: 32,
        layoutGapLg: 48,
        iconStrokeWidth: 1.5,
        scrollbarWidth: 2,
        scrollbarThumbColor: 'rgba(0, 255, 255, 0.3)',
        industrialRegistry: false,
        isNavHidden: false,
        sidebarWidth: 280,
        sidebarMinWidth: 240,
        sidebarMaxWidth: 320,
        sidebarColor: 'rgba(3, 5, 20, 0.4)',
        sidebarHoverColor: 'rgba(255, 0, 255, 0.05)',
        sidebarActiveColor: 'rgba(0, 255, 255, 0.1)',
        sidebarNoiseOpacity: 0.1,
        topbarHeight: 72,
        topbarColor: 'rgba(3, 5, 20, 0.4)',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0.1,
        topbarTitleColor: '#ffffff',
        tabGap: 16,
        tabSectionMargin: 24,
        navItemActiveColor: '#00ffff',
        navActiveMarkerColor: '#ff00ff',
        navActiveMarkerGlow: 30,
        sidebarBlur: 40,
        sidebarShadow: 'none',
        cardBorderRadius: 30,
        cardRadiusTL: 30,
        cardRadiusTR: 8,
        cardRadiusBL: 8,
        cardRadiusBR: 30,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(10, 15, 40, 0.2)',
        cardBackdropBlur: 40,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 1,
        cardBorderColor: 'rgba(0, 255, 255, 0.15)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(255, 0, 255, 0.1)',
        cardInnerGlowWidth: 2,
        cardTextureType: 'noise',
        cardTextureOpacity: 0.1,
        cardHeaderBg: 'rgba(0, 255, 255, 0.03)',
        cardHeaderBorder: 'rgba(0, 255, 255, 0.1)',
        cardHeaderPadding: 24,
        cardFooterBg: 'rgba(255, 0, 255, 0.03)',
        cardFooterBorder: 'rgba(255, 0, 255, 0.1)',
        cardShadowSpread: 60,
        cardGlowColor: 'rgba(0, 255, 255, 0.15)',
        cardGlowIntensity: 1,
        cardHoverTranslate: -6,
        cardHoverGlowIncrease: 0.4,
        cardSpotlightOpacity: 0.4,
        cardPaddingMd: 32,
        cardVariant: 'glass',
        cardTitleFontSize: 22,
        cardTitleColor: '#ffffff',
        cardTitleFontWeight: '300',
        cardTitleLetterSpacing: 1,
        cardTitleIconGlow: 'rgba(0, 255, 255, 0.6)',
        cardActionBtnPrimaryBg: 'rgba(255, 0, 255, 0.2)',
        cardActionBtnHoverBg: 'rgba(255, 0, 255, 0.4)',
        cardActionBtnText: '#ffffff',
        cardActionBtnBorderRadius: 16,
        cardActionBtnPadding: 12,
        cardActionClickScale: 0.95,
        cardSearchBgFocus: 'rgba(0, 255, 255, 0.1)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.3)',
        cardSearchTextFocusColor: '#ffffff',
        modalOverlayColor: 'rgba(3, 5, 20, 0.8)',
        modalOverlayBlur: 20,
        modalBorderRadius: 30,
        tooltipBg: 'rgba(10, 15, 40, 0.8)',
        tooltipRadius: 12,
        tableHeaderBg: 'rgba(255, 255, 255, 0.02)',
        tableRowHoverBg: 'rgba(0, 255, 255, 0.05)',
        tableCellPadding: 16,
        tableBorderColor: 'rgba(0, 255, 255, 0.05)',
        headingFont: "'Inter', sans-serif",
        bodyFont: "'Inter', sans-serif",
        monoFont: "'JetBrains Mono', monospace",
        textColorMaster: '#ffffff',
        textColorSecondary: '#00ffff',
        textColorMuted: 'rgba(255, 255, 255, 0.5)',
        h1Size: 56,
        h1Weight: '300',
        h1LineHeight: 1.2,
        h1LetterSpacing: -1,
        h2Size: 32,
        h2Weight: '300',
        h2LineHeight: 1.3,
        bodyLineHeight: 1.8,
        bodyWeight: '300',
        headingTransform: 'none',
        textSmoothing: true,
        textGlowIntensity: 0.5,
        btnBorderRadius: 20,
        btnRadiusTL: 20,
        btnRadiusTR: 20,
        btnRadiusBL: 20,
        btnRadiusBR: 20,
        btnHoverScale: 1.04,
        btnActiveScale: 0.96,
        btnPrimaryBg: 'rgba(0, 255, 255, 0.1)',
        btnPrimaryText: '#00ffff',
        btnSecondaryBg: 'rgba(255, 0, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.05)',
        btnStyleType: 'glass',
        btnNeonGlowColor: 'rgba(0, 255, 255, 0.6)',
        btnNeonPulseSpeed: 2,
        btnBackdropBlur: 20,
        inputBorderRadius: 16,
        inputBg: 'rgba(255, 255, 255, 0.02)',
        switchTrackActiveBg: '#00ffff',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#00ffff',
        switchStyleType: 'glass',
        switchBackdropBlur: 10,
        switchPulseColor: '#00ffff',
        colorPalette: 'default',
        primaryColor: '#00ffff',
        secondaryColor: '#ff00ff',
        tertiaryColor: '#0088ff',
        accentColor: '#ffffff',
        surfaceColor: 'rgba(10, 15, 40, 0.2)',
        textureColor: '#00ffff',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgBody: '#030514',
        colorBgLayer1: '#050a1f',
        colorBgLayer2: '#080d29',
        colorBgModal: 'rgba(3, 5, 20, 0.9)',
        chartColorPalette: '#00ffff',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(10, 15, 40, 0.9)',
        chartType: 'area',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: true,
        animInstant: 100,
        animFast: 300,
        animNormal: 500,
        animSlow: 800,
        easeMain: 'cubic-bezier(0.16, 1, 0.3, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        bgGradientMode: 'radial',
        bgGradientAngle: 0,
        surfaceMaterial: 'holographic',
        surfaceIntensity: 1,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'noise',
        textureOpacity: 0.1,
        atmosphereNoiseOpacity: 0.1,
        noiseIntensity: 0.1,
        bgNoiseDensity: 0.1,
        bgNoiseAnimation: 1,
        glassBlur: 60,
        glassOpacity: 0.1,
        glassSpecularity: 0.8,
        glassRoughness: 0,
        glassSaturation: 2,
        shadowIntensity: 1,
        layeredShadows: 1,
        shadowOrientation: 'center',
        shadowColorMode: 'primary',
        shadowAmbientAlpha: 0.6,
        shadowProjectionBlur: 100,
        shadowProjectionAlpha: 0.4,
        cardShadow: '0 0 50px rgba(0,255,255,0.1)',
        securityShieldGlow: 50,
        securityPulseSpeed: 2,
        vignetteOpacity: 0.6,
        vignetteSoftness: 80,
        globalSaturation: 1.5,
        globalContrast: 1.1,
        contrastCurve: 1,
        chatBubbleRadius: 20,
        chatUserBg: 'rgba(0, 255, 255, 0.1)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.02,
        statusSuccessColor: '#00ffff',
        statusErrorColor: '#ff00ff',
        statusWarningColor: '#ffff00',
        statusInfoColor: '#0088ff',
        badgeRadius: 99,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 2000,
        zIndexToast: 2000,
        aiPanelBg: 'rgba(3, 5, 20, 0.6)',
        aiGlowColor: '#ff00ff',
        flowNodeRadius: 24,
        flowGridStyle: 'dots',
        motionEaseMain: 'cubic-bezier(0.16, 1, 0.3, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.7, 0, 0.84, 0)',
        motionDurationInstant: 0.2,
        motionDurationFast: 0.4,
        motionDurationNormal: 0.6,
        motionDurationSlow: 1,
        motionStaggerDelay: 0.1,
        scrollWidth: 2,
        scrollRadius: 10,
        scrollTrackOpacity: 0,
        scrollThumbColor: '#00ffff',
        scrollThumbOpacity: 0.2,
        scrollThumbHoverOpacity: 0.5,
        scrollPadding: 4,
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 40,
        layerBackdropOpacity: 0.5,
        layerElevationFactor: 3,
        matrixGap: 32,
        matrixRadius: 30,
        matrixItemBg: 'rgba(255, 255, 255, 0.01)',
        matrixBorderColor: 'rgba(0, 255, 255, 0.1)',
        matrixSearchBg: 'rgba(10, 15, 40, 0.5)',
        matrixBlur: 40,
        colorPrimary: '#00ffff',
        colorSecondary: '#ff00ff',
        fontHeading: "'Inter', sans-serif",
        radiusTheme: '24px',
        buttonRadius: '20px',
        cardRadius: '30px',
        themeGap: '32px',
        motionSpeedBase: 500,
        pageTransition: 'fade'
    }
};
