import { ThemePreset } from './index';

/**
 * Tema Gerado Automaticamente pela Skill Sarak-UI-criar-tema
 * 
 * Siga as instruções do workflow para preencher as variáveis abaixo.
 * NUNCA adicione propriedades que não estejam mapeadas no schema oficial.
 */
export const kineticFlowTheme: ThemePreset = {
    id: 'kinetic-flow',
    name: 'Kinetic Flow',
    description: 'Tema hiper-dinâmico que utiliza uma animação fluida (vídeo) de fundo e neon vibrante.',
    design: {
        matrixGap: 12,
        matrixRadius: 12,
        matrixItemBg: 'rgba(255, 255, 255, 0.02)',
        matrixBorderColor: 'rgba(255, 255, 255, 0.05)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.05)',
        matrixBlur: 10,
        animInstant: 100,
        animFast: 200,
        animNormal: 300,
        animSlow: 500,
        easeMain: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#050505',
        colorBgLayer1: '#050010',
        colorBgLayer2: '#0a0020',
        bgBaseColor: '#030008',
        bgGradientMode: 'radial',
        bgGradientAngle: 180,
        surfaceMaterial: 'sleek',
        surfaceIntensity: 0.9,
        borderType: 'glow',
        systemTone: 'cyber',
        texture: 'waves',
        textureOpacity: 0.2,
        atmosphereNoiseOpacity: 0.05,
        noiseIntensity: 0.05,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 0.5,
        glassBlur: 16,
        glassOpacity: 0.1,
        glassSpecularity: 0.8,
        glassRoughness: 0.02,
        glassSaturation: 2,
        shadowIntensity: 1,
        layeredShadows: 2,
        shadowOrientation: 'bottom',
        shadowColorMode: 'colored',
        shadowAmbientAlpha: 0.8,
        shadowProjectionBlur: 80,
        shadowProjectionAlpha: 0.6,
        securityShieldGlow: 30,
        securityPulseSpeed: 1,
        vignetteOpacity: 0.6,
        vignetteSoftness: 100,
        globalSaturation: 1.5,
        globalContrast: 1.2,
        contrastCurve: 1.5,
        identityAlignment: 'center',
        identityPadding: 16,
        identityFontFamily: 'JetBrains Mono',
        identityFontWeight: 900,
        identityTracking: 2,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 8,
        btnRadiusTL: 8,
        btnRadiusTR: 8,
        btnRadiusBL: 8,
        btnRadiusBR: 8,
        btnHoverScale: 1.02,
        btnActiveScale: 0.98,
        btnPrimaryBg: '#ff0055',
        btnPrimaryText: '#ffffff',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.05)',
        btnStyleType: 'matte',
        btnNeonGlowColor: 'rgba(0, 242, 255, 0.4)',
        btnNeonPulseSpeed: 1.5,
        btnBackdropBlur: 8,
        cardActionBtnPrimaryBg: '#ff0055',
        cardActionBtnHoverBg: 'rgba(255, 0, 85, 0.8)',
        cardActionBtnText: '#ffffff',
        cardActionBtnBorderRadius: 0,
        cardActionBtnPadding: 10,
        cardActionClickScale: 0.98,
        cardSearchBgFocus: 'rgba(255, 0, 85, 0.1)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.3)',
        cardSearchTextFocusColor: '#ffffff',
        cardTitleFontSize: 18,
        cardTitleColor: '#ffffff',
        cardTitleFontWeight: '900',
        cardTitleLetterSpacing: 2,
        cardTitleIconGlow: 'rgba(255, 0, 85, 0.5)',
        cardBorderRadius: 0,
        cardRadiusTL: 0,
        cardRadiusTR: 20,
        cardRadiusBL: 20,
        cardRadiusBR: 0,
        cardGeometricCut: 10,
        cardBackgroundColor: 'rgba(0, 0, 0, 0.7)',
        cardBackdropBlur: 4,
        cardSurfaceOpacity: 0.9,
        cardBorderWidth: 2,
        cardBorderColor: 'rgba(255, 0, 85, 0.5)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 4,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(255, 0, 85, 0.15)',
        cardInnerGlowWidth: 1,
        cardTextureType: 'scanlines',
        cardTextureOpacity: 0.1,
        cardHeaderBg: 'rgba(255, 0, 85, 0.1)',
        cardHeaderBorder: 'rgba(255, 0, 85, 0.3)',
        cardHeaderPadding: 12,
        cardFooterBg: 'rgba(0, 0, 0, 0.5)',
        cardFooterBorder: 'rgba(255, 0, 85, 0.3)',
        cardShadowSpread: 10,
        cardGlowColor: 'rgba(255, 0, 85, 0.4)',
        cardGlowIntensity: 0.8,
        cardHoverTranslate: -2,
        cardHoverGlowIncrease: 1,
        cardSpotlightOpacity: 0.3,
        cardPaddingMd: 16,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.5,
        imageCardHoverZoom: 1.05,
        chatBubbleRadius: 12,
        chatUserBg: 'rgba(255, 255, 255, 0.05)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.05,
        colorPalette: 'default',
        primaryColor: '#ff0055',
        secondaryColor: '#00ffcc',
        tertiaryColor: '#ffff00',
        accentColor: '#ff0055',
        surfaceColor: '#1a000b',
        textureColor: '#ff0055',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(15, 15, 15, 0.8)',
        chartColorPalette: '#00f2ff',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(26, 0, 11, 0.9)',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 3,
        chartSmoothing: false,
        focusRingWidth: 3,
        reducedMotion: false,
        zIndexModal: 1000,
        zIndexToast: 2000,
        mode: 'dark',
        navigationStyle: 'sidebar',
        bodySize: '14px',
        inputBorderRadius: 8,
        inputBg: 'rgba(255, 0, 85, 0.05)',
        inputBorderColor: 'rgba(255, 0, 85, 0.2)',
        inputFocusBorderColor: '#ff0055',
        inputTextColor: '#ffffff',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 10,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4',
        globalBackgroundBlur: 0,
        globalBackgroundBlendMode: 'color-dodge',
        globalBackgroundOpacity: 0.8,
        motionEaseMain: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.05,
        motionDurationFast: 0.1,
        motionDurationNormal: 0.2,
        motionDurationSlow: 0.4,
        motionStaggerDelay: 0.02,
        isNavHidden: false,
        sidebarWidth: 200,
        sidebarMinWidth: 180,
        sidebarMaxWidth: 300,
        sidebarColor: 'rgba(0, 0, 0, 0.8)',
        sidebarHoverColor: 'rgba(255, 0, 85, 0.2)',
        sidebarActiveColor: 'rgba(255, 0, 85, 0.3)',
        sidebarNoiseOpacity: 0.1,
        topbarHeight: 56,
        topbarColor: 'rgba(0, 0, 0, 0.9)',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0.1,
        topbarTitleColor: '#ff0055',
        tabGap: 4,
        tabSectionMargin: 12,
        navItemActiveColor: '#00ffcc',
        navActiveMarkerColor: '#ff0055',
        navActiveMarkerGlow: 30,
        sidebarBlur: 5,
        sidebarShadow: '5px 0 20px rgba(255, 0, 85, 0.2)',
        searchPositionTopbar: 'left',
        searchPositionSidebar: 'bottom',
        modalOverlayColor: 'rgba(26, 0, 11, 0.8)',
        modalOverlayBlur: 2,
        modalBorderRadius: 0,
        tooltipBg: '#ff0055',
        tooltipRadius: 0,
        scrollWidth: 4,
        scrollRadius: 0,
        scrollTrackOpacity: 0.2,
        scrollThumbColor: '#ff0055',
        scrollThumbOpacity: 0.8,
        scrollThumbHoverOpacity: 1,
        scrollPadding: 0,
        aiPanelBg: 'rgba(0, 0, 0, 0.8)',
        aiGlowColor: '#00ffcc',
        flowNodeRadius: 0,
        flowGridStyle: 'lines',
        statusSuccessColor: '#00ffcc',
        statusErrorColor: '#ff0055',
        statusWarningColor: '#ffff00',
        statusInfoColor: '#00f2ff',
        badgeRadius: 0,
        switchTrackActiveBg: '#ff0055',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#ff0055',
        switchStyleType: 'tactile',
        switchBackdropBlur: 2,
        switchPulseColor: '#ff0055',
        layout: 'grid',
        layoutDensity: 'compact',
        maxContentWidth: '1200px',
        layoutPadding: 16,
        isSplitViewEnabled: false,
        isAutoHideEnabled: true,
        borderRadius: 0,
        borderRadiusSm: 0,
        borderRadiusMd: 0,
        borderRadiusLg: 0,
        borderWidth: 2,
        borderStyle: 'solid',
        layoutGap: 16,
        layoutGapSm: 8,
        layoutGapMd: 16,
        layoutGapLg: 24,
        iconFamily: 'lucide',
        iconWeight: 'bold',
        iconStrokeWidth: 2.5,
        scrollbarWidth: 4,
        scrollbarThumbColor: '#ff0055',
        industrialRegistry: true,
        tableHeaderBg: 'rgba(255, 0, 85, 0.1)',
        tableRowHoverBg: 'rgba(255, 0, 85, 0.05)',
        tableCellPadding: 8,
        tableBorderColor: 'rgba(255, 0, 85, 0.3)',
        headingFont: '\'JetBrains Mono\', monospace',
        bodyFont: '\'JetBrains Mono\', monospace',
        monoFont: '\'JetBrains Mono\', monospace',
        textColorMaster: '#ffffff',
        textColorSecondary: '#ffb3cc',
        textColorMuted: '#660022',
        h1Size: 36,
        h1Weight: '900',
        h1LineHeight: 1.0,
        h1LetterSpacing: 4,
        h2Size: 24,
        h2Weight: '800',
        h2LineHeight: 1.1,
        bodyLineHeight: 1.4,
        bodyWeight: '500',
        headingTransform: 'uppercase',
        textSmoothing: false,
        textGlowIntensity: 0.8
    }
};
