import { ThemePreset } from './index';

export const nebulaSpaceTheme: ThemePreset = {
    id: 'nebula-space',
    name: 'Nebula Space',
    description: 'Imersivo & Cyberpunk: Imagem de fundo, transições de Zoom e Ícones Duotone com alto desfoque de vidro e componentes centralizados.',
    design: {
        mode: 'dark',
        navigationStyle: 'topbar',
        bodySize: '13px',
        iconFamily: 'phosphor',
        iconWeight: 'duotone',
        systemName: 'Nebula OS',
        logoUrl: '',
        logoMinimalUrl: '',
        logoScale: 100,
        identityAlignment: 'left',
        identityPadding: 16,
        identityFontFamily: 'Inter',
        identityFontWeight: 700,
        identityTracking: 0,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        bgBaseColor: '#020205',
        layout: 'grid',
        layoutDensity: 'compact',
        maxContentWidth: '1440px',
        layoutPadding: 32,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 12,
        borderRadiusSm: 6,
        borderRadiusMd: 12,
        borderRadiusLg: 20,
        borderWidth: 1,
        borderStyle: 'solid',
        layoutGap: 24,
        layoutGapSm: 12,
        layoutGapMd: 24,
        layoutGapLg: 36,
        iconStrokeWidth: 2,
        scrollbarWidth: 6,
        scrollbarThumbColor: 'rgba(255, 255, 255, 0.1)',
        industrialRegistry: true,
        isNavHidden: false,
        sidebarWidth: 240,
        sidebarMinWidth: 200,
        sidebarMaxWidth: 450,
        sidebarColor: 'rgba(5, 5, 10, 0.5)',
        sidebarHoverColor: 'transparent',
        sidebarActiveColor: 'transparent',
        sidebarNoiseOpacity: 0,
        topbarHeight: 64,
        topbarColor: 'rgba(5, 5, 10, 0.5)',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0,
        topbarTitleColor: '#00e5ff',
        tabGap: 8,
        tabSectionMargin: 16,
        navItemActiveColor: '#ff007f',
        navActiveMarkerColor: '#ff007f',
        navActiveMarkerGlow: 10,
        sidebarBlur: 10,
        sidebarShadow: '10px 0 30px rgba(0,0,0,0.5)',
        searchPositionTopbar: 'center',
        searchPositionSidebar: 'hidden',
        cardBorderRadius: 24,
        cardRadiusTL: 24,
        cardRadiusTR: 24,
        cardRadiusBL: 24,
        cardRadiusBR: 24,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(20, 20, 40, 0.2)',
        cardBackdropBlur: 20,
        cardSurfaceOpacity: 0.8,
        cardBorderWidth: 1,
        cardBorderColor: 'rgba(0, 229, 255, 0.2)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(255, 255, 255, 0.05)',
        cardInnerGlowWidth: 1,
        cardTextureType: 'none',
        cardTextureOpacity: 0.03,
        cardHeaderBg: 'rgba(255, 255, 255, 0.03)',
        cardHeaderBorder: 'rgba(255, 255, 255, 0.05)',
        cardHeaderPadding: 16,
        cardFooterBg: 'transparent',
        cardFooterBorder: 'rgba(255, 255, 255, 0.05)',
        cardShadowSpread: 20,
        cardGlowColor: 'rgba(255, 0, 127, 0.05)',
        cardGlowIntensity: 0,
        cardHoverTranslate: -4,
        cardHoverGlowIncrease: 0.2,
        cardSpotlightOpacity: 0.1,
        cardPaddingMd: 24,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.7,
        imageCardHoverZoom: 1.15,
        cardTitleFontSize: 20,
        cardTitleColor: '#ff007f',
        cardTitleFontWeight: '900',
        cardTitleLetterSpacing: 0,
        cardTitleIconGlow: 'rgba(255, 0, 127, 0.2)',
        cardActionBtnPrimaryBg: '#ff007f',
        cardActionBtnHoverBg: 'rgba(255, 0, 127, 0.8)',
        cardActionBtnText: '#090d16',
        cardActionBtnBorderRadius: 12,
        cardActionBtnPadding: 12,
        cardActionClickScale: 0.96,
        cardSearchBgFocus: 'rgba(255, 0, 127, 0.08)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.4)',
        cardSearchTextFocusColor: '#ffffff',
        modalOverlayColor: 'rgba(0, 0, 0, 0.4)',
        modalOverlayBlur: 8,
        modalBorderRadius: 16,
        tooltipBg: '#0f172a',
        tooltipRadius: 4,
        tableHeaderBg: 'rgba(255, 255, 255, 0.03)',
        tableRowHoverBg: 'rgba(255, 255, 255, 0.02)',
        tableCellPadding: 12,
        tableBorderColor: 'rgba(255, 255, 255, 0.05)',
        headingFont: "'Outfit', sans-serif",
        bodyFont: "'Inter', sans-serif",
        monoFont: "'JetBrains Mono', monospace",
        textColorMaster: '#ffffff',
        textColorSecondary: 'rgba(255, 255, 255, 0.8)',
        textColorMuted: 'rgba(255, 255, 255, 0.5)',
        h1Size: 42,
        h1Weight: '900',
        h1LineHeight: 1.1,
        h1LetterSpacing: -1,
        h2Size: 32,
        h2Weight: '700',
        h2LineHeight: 1.2,
        bodyLineHeight: 1.6,
        bodyWeight: '400',
        headingTransform: 'none',
        textSmoothing: true,
        textGlowIntensity: 0,
        btnBorderRadius: 12,
        btnRadiusTL: 12,
        btnRadiusTR: 12,
        btnRadiusBL: 12,
        btnRadiusBR: 12,
        btnHoverScale: 1.02,
        btnActiveScale: 0.98,
        btnPrimaryBg: '#ff007f',
        btnPrimaryText: '#000000',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.05)',
        btnStyleType: 'matte',
        btnNeonGlowColor: 'rgba(255, 0, 127, 0.4)',
        btnNeonPulseSpeed: 1.5,
        btnBackdropBlur: 8,
        inputBorderRadius: 12,
        inputBg: 'rgba(255, 255, 255, 0.03)',
        inputBorderColor: 'rgba(255, 0, 127, 0.2)',
        inputFocusBorderColor: '#ff007f',
        inputTextColor: '#ffffff',
        switchTrackActiveBg: '#ff007f',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#ff007f',
        switchStyleType: 'tactile',
        switchBackdropBlur: 4,
        switchPulseColor: '#ff007f',
        colorPalette: 'default',
        primaryColor: '#ff007f',
        secondaryColor: '#00e5ff',
        tertiaryColor: '#10b981',
        accentColor: '#ff00d4',
        surfaceColor: 'rgba(10, 10, 20, 0.4)',
        textureColor: '#ffffff',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgBody: '#020205',
        colorBgLayer1: '#0f0f0f',
        colorBgLayer2: '#1a1a1a',
        colorBgModal: 'rgba(15, 15, 15, 0.8)',
        chartColorPalette: '#ff007f',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(15, 23, 42, 0.9)',
        chartType: 'line',
        chartShowGrid: true,
        chartThickness: 2,
        chartSmoothing: true,
        animInstant: 100,
        animFast: 200,
        animNormal: 300,
        animSlow: 500,
        easeMain: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'zoom',
        cardHoverStyle: '3d-tilt',
        bgGradientMode: 'linear',
        bgGradientAngle: 135,
        surfaceMaterial: 'frosted',
        surfaceIntensity: 0.5,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'grid',
        textureOpacity: 0.1,
        atmosphereNoiseOpacity: 0.05,
        noiseIntensity: 0.05,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 1,
        glassBlur: 20,
        glassOpacity: 0.1,
        glassSpecularity: 0.1,
        glassRoughness: 0.05,
        glassSaturation: 1.8,
        shadowIntensity: 0.5,
        layeredShadows: 1,
        shadowOrientation: 'bottom',
        shadowColorMode: 'neutral',
        shadowAmbientAlpha: 0.4,
        shadowProjectionBlur: 40,
        shadowProjectionAlpha: 0.2,
        securityShieldGlow: 10,
        securityPulseSpeed: 2,
        vignetteOpacity: 0.3,
        vignetteSoftness: 50,
        globalSaturation: 1,
        globalContrast: 1,
        contrastCurve: 1,
        chatBubbleRadius: 12,
        chatUserBg: 'rgba(255, 255, 255, 0.05)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.05,
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#3b82f6',
        badgeRadius: 99,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 2000,
        zIndexToast: 2000,
        aiPanelBg: 'rgba(0, 0, 0, 0.4)',
        aiGlowColor: '#ff007f',
        flowNodeRadius: 12,
        flowGridStyle: 'dots',
        motionEaseMain: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.1,
        motionDurationFast: 0.2,
        motionDurationNormal: 0.3,
        motionDurationSlow: 0.6,
        motionStaggerDelay: 0.05,
        scrollWidth: 6,
        scrollRadius: 10,
        scrollTrackOpacity: 0.05,
        scrollThumbColor: '#ffffff',
        scrollThumbOpacity: 0.2,
        scrollThumbHoverOpacity: 0.5,
        scrollPadding: 2,
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 10,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        matrixGap: 12,
        matrixRadius: 12,
        matrixItemBg: 'rgba(255, 255, 255, 0.02)',
        matrixBorderColor: 'rgba(255, 255, 255, 0.05)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.05)',
        matrixBlur: 10,
        globalBackgroundImageUrl: 'url("https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1920&auto=format&fit=crop")',
        globalBackgroundBlur: 4,
        globalBackgroundBlendMode: 'screen',
        globalBackgroundOpacity: 0.25,
        bgBase: '#020205',
        fontHeading: "'Outfit', sans-serif",
        radiusTheme: '16px',
        buttonRadius: '12px',
        cardRadius: '24px',
        themeGap: '12px',
        motionSpeedBase: 500,
        pageTransition: 'zoom'
    }
};
