import { ThemePreset } from './index';

/**
 * Tema Gerado Automaticamente pela Skill Sarak-UI-criar-tema
 * 
 * Siga as instruções do workflow para preencher as variáveis abaixo.
 * NUNCA adicione propriedades que não estejam mapeadas no schema oficial.
 */
export const stellarNebulaTheme: ThemePreset = {
    id: 'stellar-nebula',
    name: 'Stellar Nebula',
    description: 'Tema espacial imersivo com background real, cores cósmicas e alto glassmorphism.',
    design: {
        matrixGap: 12,
        matrixRadius: 12,
        matrixItemBg: 'rgba(255, 255, 255, 0.02)',
        matrixBorderColor: 'rgba(255, 255, 255, 0.05)',
        matrixSearchBg: 'rgba(255, 255, 255, 0.05)',
        matrixBlur: 10,
        animInstant: 100,
        animFast: 200,
        animNormal: 300,
        animSlow: 500,
        easeMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        animEnabled: true,
        pageTransitionType: 'fade',
        cardHoverStyle: 'lift',
        colorBgBody: '#050505',
        colorBgLayer1: '#090909',
        colorBgLayer2: '#121212',
        bgBaseColor: '#050505',
        bgGradientMode: 'radial',
        bgGradientAngle: 135,
        surfaceMaterial: 'frosted',
        surfaceIntensity: 0.8,
        borderType: 'glow',
        systemTone: 'cyber',
        texture: 'none',
        textureOpacity: 0.1,
        atmosphereNoiseOpacity: 0.05,
        noiseIntensity: 0.05,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 1,
        glassBlur: 24,
        glassOpacity: 0.05,
        glassSpecularity: 0.5,
        glassRoughness: 0.05,
        glassSaturation: 1.5,
        shadowIntensity: 0.8,
        layeredShadows: 1,
        shadowOrientation: 'center',
        shadowColorMode: 'colored',
        shadowAmbientAlpha: 0.6,
        shadowProjectionBlur: 60,
        shadowProjectionAlpha: 0.4,
        securityShieldGlow: 20,
        securityPulseSpeed: 4,
        vignetteOpacity: 0.5,
        vignetteSoftness: 80,
        globalSaturation: 1.2,
        globalContrast: 1.1,
        contrastCurve: 1.2,
        identityAlignment: 'left',
        identityPadding: 16,
        identityFontFamily: 'Outfit',
        identityFontWeight: 700,
        identityTracking: 0,
        identityRedirectUrl: '/',
        identityHoverEffect: 'opacity',
        btnBorderRadius: 8,
        btnRadiusTL: 8,
        btnRadiusTR: 8,
        btnRadiusBL: 8,
        btnRadiusBR: 8,
        btnHoverScale: 1.02,
        btnActiveScale: 0.98,
        btnPrimaryBg: '#8b5cf6',
        btnPrimaryText: '#ffffff',
        btnSecondaryBg: 'rgba(255, 255, 255, 0.05)',
        btnGhostHoverBg: 'rgba(255, 255, 255, 0.05)',
        btnStyleType: 'matte',
        btnNeonGlowColor: 'rgba(0, 242, 255, 0.4)',
        btnNeonPulseSpeed: 1.5,
        btnBackdropBlur: 8,
        cardActionBtnPrimaryBg: '#8b5cf6',
        cardActionBtnHoverBg: 'rgba(139, 92, 246, 0.8)',
        cardActionBtnText: '#ffffff',
        cardActionBtnBorderRadius: 16,
        cardActionBtnPadding: 16,
        cardActionClickScale: 0.92,
        cardSearchBgFocus: 'rgba(139, 92, 246, 0.15)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 255, 255, 0.5)',
        cardSearchTextFocusColor: '#ffffff',
        cardTitleFontSize: 24,
        cardTitleColor: '#e2e8f0',
        cardTitleFontWeight: '700',
        cardTitleLetterSpacing: 1,
        cardTitleIconGlow: 'rgba(139, 92, 246, 0.4)',
        cardBorderRadius: 24,
        cardRadiusTL: 24,
        cardRadiusTR: 24,
        cardRadiusBL: 24,
        cardRadiusBR: 24,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(15, 23, 42, 0.4)',
        cardBackdropBlur: 30,
        cardSurfaceOpacity: 0.6,
        cardBorderWidth: 2,
        cardBorderColor: 'rgba(139, 92, 246, 0.3)',
        cardBorderOpacity: 1,
        cardBorderTop: 1,
        cardBorderBottom: 1,
        cardBorderLeft: 1,
        cardBorderRight: 1,
        cardInnerGlowColor: 'rgba(139, 92, 246, 0.1)',
        cardInnerGlowWidth: 2,
        cardTextureType: 'noise',
        cardTextureOpacity: 0.05,
        cardHeaderBg: 'rgba(255, 255, 255, 0.02)',
        cardHeaderBorder: 'rgba(139, 92, 246, 0.2)',
        cardHeaderPadding: 20,
        cardFooterBg: 'rgba(0, 0, 0, 0.2)',
        cardFooterBorder: 'rgba(139, 92, 246, 0.2)',
        cardShadowSpread: 40,
        cardGlowColor: 'rgba(139, 92, 246, 0.2)',
        cardGlowIntensity: 0.5,
        cardHoverTranslate: -8,
        cardHoverGlowIncrease: 0.5,
        cardSpotlightOpacity: 0.2,
        cardPaddingMd: 32,
        cardVariant: 'classic',
        imageCardOverlayOpacity: 0.5,
        imageCardHoverZoom: 1.05,
        chatBubbleRadius: 12,
        chatUserBg: 'rgba(255, 255, 255, 0.05)',
        chatBubbleStyle: 'glass',
        chatAnimationSpeed: 0.05,
        colorPalette: 'default',
        primaryColor: '#8b5cf6',
        secondaryColor: '#ec4899',
        tertiaryColor: '#3b82f6',
        accentColor: '#06b6d4',
        surfaceColor: '#0f172a',
        textureColor: '#8b5cf6',
        titleColor: '#ffffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgModal: 'rgba(15, 15, 15, 0.8)',
        chartColorPalette: '#00f2ff',
        chartGridOpacity: 0.05,
        chartTooltipBg: 'rgba(15, 23, 42, 0.9)',
        chartType: 'area',
        chartShowGrid: false,
        chartThickness: 2,
        chartSmoothing: true,
        focusRingWidth: 2,
        reducedMotion: false,
        zIndexModal: 1000,
        zIndexToast: 2000,
        mode: 'dark',
        navigationStyle: 'sidebar',
        bodySize: '14px',
        inputBorderRadius: 8,
        inputBg: 'rgba(255, 255, 255, 0.03)',
        inputBorderColor: 'rgba(255, 255, 255, 0.1)',
        inputFocusBorderColor: '#8b5cf6',
        inputTextColor: '#ffffff',
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 10,
        layerBackdropOpacity: 0.4,
        layerElevationFactor: 1,
        globalBackgroundImageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=1920&auto=format&fit=crop',
        globalBackgroundBlur: 4,
        globalBackgroundBlendMode: 'screen',
        globalBackgroundOpacity: 0.6,
        motionEaseMain: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
        motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
        motionDurationInstant: 0.15,
        motionDurationFast: 0.3,
        motionDurationNormal: 0.5,
        motionDurationSlow: 0.8,
        motionStaggerDelay: 0.1,
        isNavHidden: false,
        sidebarWidth: 280,
        sidebarMinWidth: 240,
        sidebarMaxWidth: 400,
        sidebarColor: 'rgba(15, 23, 42, 0.5)',
        sidebarHoverColor: 'rgba(139, 92, 246, 0.1)',
        sidebarActiveColor: 'rgba(139, 92, 246, 0.2)',
        sidebarNoiseOpacity: 0.05,
        topbarHeight: 80,
        topbarColor: 'rgba(15, 23, 42, 0.5)',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0.05,
        topbarTitleColor: '#e2e8f0',
        tabGap: 16,
        tabSectionMargin: 24,
        navItemActiveColor: '#8b5cf6',
        navActiveMarkerColor: '#8b5cf6',
        navActiveMarkerGlow: 20,
        sidebarBlur: 20,
        sidebarShadow: '10px 0 50px rgba(139, 92, 246, 0.1)',
        searchPositionTopbar: 'center',
        searchPositionSidebar: 'hidden',
        modalOverlayColor: 'rgba(15, 23, 42, 0.8)',
        modalOverlayBlur: 16,
        modalBorderRadius: 24,
        tooltipBg: 'rgba(139, 92, 246, 0.9)',
        tooltipRadius: 8,
        scrollWidth: 8,
        scrollRadius: 12,
        scrollTrackOpacity: 0.1,
        scrollThumbColor: '#8b5cf6',
        scrollThumbOpacity: 0.4,
        scrollThumbHoverOpacity: 0.8,
        scrollPadding: 4,
        aiPanelBg: 'rgba(15, 23, 42, 0.6)',
        aiGlowColor: '#8b5cf6',
        flowNodeRadius: 20,
        flowGridStyle: 'lines',
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#8b5cf6',
        badgeRadius: 8,
        switchTrackActiveBg: '#8b5cf6',
        switchThumbBg: '#ffffff',
        checkboxActiveColor: '#8b5cf6',
        switchStyleType: 'tactile',
        switchBackdropBlur: 8,
        switchPulseColor: '#8b5cf6',
        layout: 'masonry',
        layoutDensity: 'spacious',
        maxContentWidth: '1600px',
        layoutPadding: 48,
        isSplitViewEnabled: true,
        isAutoHideEnabled: false,
        borderRadius: 24,
        borderRadiusSm: 12,
        borderRadiusMd: 24,
        borderRadiusLg: 32,
        borderWidth: 2,
        borderStyle: 'dashed',
        layoutGap: 32,
        layoutGapSm: 16,
        layoutGapMd: 32,
        layoutGapLg: 48,
        iconFamily: 'phosphor',
        iconWeight: 'duotone',
        iconStrokeWidth: 1.5,
        scrollbarWidth: 8,
        scrollbarThumbColor: 'rgba(139, 92, 246, 0.3)',
        industrialRegistry: false,
        tableHeaderBg: 'rgba(139, 92, 246, 0.1)',
        tableRowHoverBg: 'rgba(139, 92, 246, 0.05)',
        tableCellPadding: 16,
        tableBorderColor: 'rgba(139, 92, 246, 0.2)',
        headingFont: '\'Outfit\', sans-serif',
        bodyFont: '\'Inter\', sans-serif',
        monoFont: '\'Fira Code\', monospace',
        textColorMaster: '#f8fafc',
        textColorSecondary: '#cbd5e1',
        textColorMuted: '#64748b',
        h1Size: 64,
        h1Weight: '800',
        h1LineHeight: 1.0,
        h1LetterSpacing: -2,
        h2Size: 40,
        h2Weight: '700',
        h2LineHeight: 1.1,
        bodyLineHeight: 1.8,
        bodyWeight: '300',
        headingTransform: 'uppercase',
        textSmoothing: true,
        textGlowIntensity: 0.2
    }
};
