import { ThemePreset } from './index';

export const synthwaveRetroTheme: ThemePreset = {
    id: 'synthwave-retro',
    name: 'Synthwave Retro',
    description: 'Neon retro-futuristic aesthetic. Asymmetrical borders, grid backgrounds, heavy glows, and vibrant 80s colors.',
    design: {
        mode: 'dark',
        navigationStyle: 'topbar',
        bodySize: '14px',
        systemName: 'Synth OS',
        logoUrl: '',
        logoMinimalUrl: '',
        logoScale: 100,
        identityAlignment: 'center',
        identityPadding: 24,
        identityFontFamily: 'JetBrains Mono',
        identityFontWeight: 900,
        identityTracking: 4,
        identityRedirectUrl: '/',
        identityHoverEffect: 'glow',
        bgBaseColor: '#090014',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1200px',
        layoutPadding: 24,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 0,
        borderRadiusSm: 0,
        borderRadiusMd: 0,
        borderRadiusLg: 0,
        borderWidth: 2,
        borderStyle: 'solid',
        layoutGap: 32,
        layoutGapSm: 16,
        layoutGapMd: 32,
        layoutGapLg: 48,
        iconStrokeWidth: 2,
        scrollbarWidth: 8,
        scrollbarThumbColor: '#ff00ff',
        industrialRegistry: false,
        isNavHidden: false,
        sidebarWidth: 260,
        sidebarMinWidth: 260,
        sidebarMaxWidth: 260,
        sidebarColor: '#12002b',
        sidebarHoverColor: 'rgba(255, 0, 255, 0.1)',
        sidebarActiveColor: 'rgba(0, 255, 255, 0.2)',
        sidebarNoiseOpacity: 0.1,
        topbarHeight: 80,
        topbarColor: '#090014',
        topbarHoverColor: 'transparent',
        topbarActiveColor: 'transparent',
        topbarNoiseOpacity: 0.2,
        topbarTitleColor: '#00ffff',
        tabGap: 16,
        tabSectionMargin: 24,
        navItemActiveColor: '#00ffff',
        navActiveMarkerColor: '#ff00ff',
        navActiveMarkerGlow: 20,
        sidebarBlur: 0,
        sidebarShadow: '5px 0 20px rgba(255,0,255,0.3)',
        cardBorderRadius: 24,
        cardRadiusTL: 24,
        cardRadiusTR: 0,
        cardRadiusBL: 0,
        cardRadiusBR: 24,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(18, 0, 43, 0.8)',
        cardBackdropBlur: 4,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 2,
        cardBorderColor: '#00ffff',
        cardBorderOpacity: 1,
        cardBorderTop: 2,
        cardBorderBottom: 2,
        cardBorderLeft: 0,
        cardBorderRight: 0,
        cardInnerGlowColor: 'rgba(255, 0, 255, 0.2)',
        cardInnerGlowWidth: 2,
        cardTextureType: 'grid',
        cardTextureOpacity: 0.3,
        cardHeaderBg: 'rgba(255, 0, 255, 0.1)',
        cardHeaderBorder: '#00ffff',
        cardHeaderPadding: 20,
        cardFooterBg: 'rgba(0, 255, 255, 0.05)',
        cardFooterBorder: '#ff00ff',
        cardShadowSpread: 15,
        cardGlowColor: 'rgba(255, 0, 255, 0.4)',
        cardGlowIntensity: 1,
        cardHoverTranslate: -8,
        cardHoverGlowIncrease: 0.5,
        cardSpotlightOpacity: 0.3,
        cardPaddingMd: 24,
        cardVariant: 'classic',
        cardTitleFontSize: 24,
        cardTitleColor: '#00ffff',
        cardTitleFontWeight: '900',
        cardTitleLetterSpacing: 2,
        cardTitleIconGlow: 'rgba(255, 0, 255, 0.8)',
        cardActionBtnPrimaryBg: '#ff00ff',
        cardActionBtnHoverBg: '#00ffff',
        cardActionBtnText: '#000000',
        cardActionBtnBorderRadius: 0,
        cardActionBtnPadding: 16,
        cardActionClickScale: 0.9,
        cardSearchBgFocus: 'rgba(255, 0, 255, 0.1)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(0, 255, 255, 0.5)',
        cardSearchTextFocusColor: '#00ffff',
        modalOverlayColor: 'rgba(9, 0, 20, 0.9)',
        modalOverlayBlur: 2,
        modalBorderRadius: 0,
        tooltipBg: '#ff00ff',
        tooltipRadius: 0,
        tableHeaderBg: 'rgba(0, 255, 255, 0.1)',
        tableRowHoverBg: 'rgba(255, 0, 255, 0.1)',
        tableCellPadding: 16,
        tableBorderColor: '#ff00ff',
        headingFont: "'JetBrains Mono', monospace",
        bodyFont: "'Inter', sans-serif",
        monoFont: "'JetBrains Mono', monospace",
        textColorMaster: '#ffffff',
        textColorSecondary: '#00ffff',
        textColorMuted: 'rgba(255, 0, 255, 0.6)',
        h1Size: 64,
        h1Weight: '900',
        h1LineHeight: 1,
        h1LetterSpacing: 4,
        h2Size: 36,
        h2Weight: '900',
        h2LineHeight: 1.2,
        bodyLineHeight: 1.8,
        bodyWeight: '400',
        headingTransform: 'uppercase',
        textSmoothing: false,
        textGlowIntensity: 1,
        btnBorderRadius: 0,
        btnRadiusTL: 16,
        btnRadiusTR: 0,
        btnRadiusBL: 0,
        btnRadiusBR: 16,
        btnHoverScale: 1.05,
        btnActiveScale: 0.95,
        btnPrimaryBg: '#ff00ff',
        btnPrimaryText: '#ffffff',
        btnSecondaryBg: 'rgba(0, 255, 255, 0.1)',
        btnGhostHoverBg: 'rgba(255, 0, 255, 0.2)',
        btnStyleType: 'outline',
        btnNeonGlowColor: 'rgba(255, 0, 255, 0.8)',
        btnNeonPulseSpeed: 0.5,
        btnBackdropBlur: 0,
        inputBorderRadius: 0,
        inputBg: '#090014',
        switchTrackActiveBg: '#ff00ff',
        switchThumbBg: '#00ffff',
        checkboxActiveColor: '#ff00ff',
        switchStyleType: 'tactile',
        switchBackdropBlur: 0,
        switchPulseColor: '#00ffff',
        colorPalette: 'default',
        primaryColor: '#ff00ff',
        secondaryColor: '#00ffff',
        tertiaryColor: '#ffff00',
        accentColor: '#ff0055',
        surfaceColor: '#12002b',
        textureColor: '#ff00ff',
        titleColor: '#00ffff',
        colorDepth: 1,
        colorVariation: 1,
        colorBgBody: '#090014',
        colorBgLayer1: '#12002b',
        colorBgLayer2: '#1c0040',
        colorBgModal: 'rgba(9, 0, 20, 0.95)',
        chartColorPalette: '#ff00ff',
        chartGridOpacity: 0.2,
        chartTooltipBg: '#12002b',
        chartType: 'bar',
        chartShowGrid: true,
        chartThickness: 4,
        chartSmoothing: false,
        animInstant: 50,
        animFast: 100,
        animNormal: 200,
        animSlow: 400,
        easeMain: 'linear',
        easeOut: 'linear',
        animEnabled: true,
        bgGradientMode: 'linear',
        bgGradientAngle: 180,
        surfaceMaterial: 'solid',
        surfaceIntensity: 1,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'grid',
        textureOpacity: 0.5,
        atmosphereNoiseOpacity: 0.2,
        noiseIntensity: 0.2,
        bgNoiseDensity: 0.1,
        bgNoiseAnimation: 1,
        glassBlur: 0,
        glassOpacity: 1,
        glassSpecularity: 0,
        glassRoughness: 1,
        glassSaturation: 1,
        shadowIntensity: 1,
        layeredShadows: 0,
        shadowOrientation: 'bottom-right',
        shadowColorMode: 'primary',
        shadowAmbientAlpha: 0.8,
        shadowProjectionBlur: 0,
        shadowProjectionAlpha: 1,
        securityShieldGlow: 20,
        securityPulseSpeed: 1,
        vignetteOpacity: 0.8,
        vignetteSoftness: 100,
        globalSaturation: 2,
        globalContrast: 1.5,
        contrastCurve: 1.2,
        chatBubbleRadius: 0,
        chatUserBg: '#ff00ff',
        chatBubbleStyle: 'solid',
        chatAnimationSpeed: 0.1,
        statusSuccessColor: '#00ffff',
        statusErrorColor: '#ff0055',
        statusWarningColor: '#ffff00',
        statusInfoColor: '#ff00ff',
        badgeRadius: 0,
        focusRingWidth: 4,
        reducedMotion: true,
        zIndexModal: 2000,
        zIndexToast: 2000,
        aiPanelBg: '#090014',
        aiGlowColor: '#ff00ff',
        flowNodeRadius: 0,
        flowGridStyle: 'lines',
        motionEaseMain: 'linear',
        motionEaseOut: 'linear',
        motionEaseIn: 'linear',
        motionDurationInstant: 0.1,
        motionDurationFast: 0.1,
        motionDurationNormal: 0.2,
        motionDurationSlow: 0.4,
        motionStaggerDelay: 0.1,
        scrollWidth: 12,
        scrollRadius: 0,
        scrollTrackOpacity: 0.2,
        scrollThumbColor: '#ff00ff',
        scrollThumbOpacity: 1,
        scrollThumbHoverOpacity: 1,
        scrollPadding: 0,
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 0,
        layerBackdropOpacity: 0.9,
        layerElevationFactor: 2,
        matrixGap: 24,
        matrixRadius: 0,
        matrixItemBg: '#12002b',
        matrixBorderColor: '#00ffff',
        matrixSearchBg: '#090014',
        matrixBlur: 0,
        colorPrimary: '#ff00ff',
        colorSecondary: '#00ffff',
        fontHeading: "'JetBrains Mono', monospace",
        radiusTheme: '0px',
        buttonRadius: '0px',
        cardRadius: '0px',
        themeGap: '32px',
        motionSpeedBase: 200,
        pageTransition: 'none'
    }
};
