import { ThemePreset } from './index';

export const synthwaveRetroTheme: ThemePreset = {
    id: 'synthwave-retro',
    name: 'Synthwave Retro',
    description: 'Pôr do sol outrun: sol laranja sobre céu de dusk em ameixa, grid retrô no horizonte, tipografia monoespaçada.',
    design: {
        mode: 'dark',
        navigationStyle: 'topbar',
        bodySize: '14px',
        iconFamily: 'phosphor',
        iconWeight: 'fill',
        identityAlignment: 'center',
        identityPadding: 24,
        identityFontFamily: 'JetBrains Mono',
        identityFontWeight: 900,
        identityTracking: 4,
        identityRedirectUrl: '/',
        identityHoverEffect: 'glow',
        bgBaseColor: '#6b2456',
        layout: 'grid',
        layoutDensity: 'comfortable',
        maxContentWidth: '1200px',
        layoutPadding: 24,
        isSplitViewEnabled: false,
        isAutoHideEnabled: false,
        borderRadius: 0,
        borderRadiusSm: 0,
        borderRadiusMd: 0,
        borderRadiusLg: 0,
        borderWidth: 2,
        borderStyle: 'solid',
        layoutGap: 32,
        layoutGapSm: 16,
        layoutGapMd: 32,
        layoutGapLg: 48,
        iconStrokeWidth: 2,
        scrollbarWidth: 8,
        scrollbarThumbColor: '#ff6b35',
        industrialRegistry: false,
        isNavHidden: false,
        sidebarWidth: 260,
        sidebarMinWidth: 260,
        sidebarMaxWidth: 260,
        sidebarColor: '#4a1942',
        sidebarHoverColor: 'rgba(255, 107, 53, 0.12)',
        sidebarActiveColor: '#ffb238',
        sidebarNoiseOpacity: 0.1,
        topbarHeight: 80,
        topbarColor: '#4a1942',
        topbarHoverColor: 'rgba(255, 107, 53, 0.12)',
        topbarActiveColor: '#ffb238',
        topbarNoiseOpacity: 0.2,
        topbarTitleColor: '#ffb238',
        tabGap: 16,
        tabSectionMargin: 24,
        navItemActiveColor: '#1a0612',
        navActiveMarkerColor: '#ffb238',
        navActiveMarkerGlow: 20,
        sidebarBlur: 0,
        sidebarShadow: '5px 0 20px rgba(255,107,53,0.25)',
        cardBorderRadius: 24,
        cardRadiusTL: 24,
        cardRadiusTR: 0,
        cardRadiusBL: 0,
        cardRadiusBR: 24,
        cardGeometricCut: 0,
        cardBackgroundColor: 'rgba(74, 25, 66, 0.8)',
        cardBackdropBlur: 4,
        cardSurfaceOpacity: 1,
        cardBorderWidth: 2,
        cardBorderColor: '#ff6b35',
        cardBorderOpacity: 1,
        cardBorderTop: 2,
        cardBorderBottom: 2,
        cardBorderLeft: 0,
        cardBorderRight: 0,
        cardInnerGlowColor: 'rgba(255, 178, 56, 0.2)',
        cardInnerGlowWidth: 2,
        cardTextureType: 'grid',
        cardTextureOpacity: 0.2,
        cardHeaderBg: 'rgba(255, 107, 53, 0.1)',
        cardHeaderBorder: '#ff6b35',
        cardHeaderPadding: 20,
        cardFooterBg: 'rgba(255, 178, 56, 0.06)',
        cardFooterBorder: '#ffb238',
        cardShadowSpread: 15,
        cardGlowColor: 'rgba(255, 107, 53, 0.35)',
        cardGlowIntensity: 1,
        cardHoverTranslate: -8,
        cardHoverGlowIncrease: 0.5,
        cardSpotlightOpacity: 0.3,
        cardPaddingMd: 24,
        cardVariant: 'classic',
        cardTitleFontSize: 24,
        cardTitleColor: '#ffb238',
        cardTitleFontWeight: '900',
        cardTitleLetterSpacing: 2,
        cardTitleIconGlow: 'rgba(255, 107, 53, 0.6)',
        cardActionBtnPrimaryBg: '#ff6b35',
        cardActionBtnHoverBg: '#ffb238',
        cardActionBtnText: '#1a0612',
        cardActionBtnBorderRadius: 0,
        cardActionBtnPadding: 16,
        cardActionClickScale: 0.9,
        cardSearchBgFocus: 'rgba(255, 107, 53, 0.1)',
        cardSearchBorderBeamActive: true,
        cardSearchPlaceholderColor: 'rgba(255, 235, 220, 0.5)',
        cardSearchTextFocusColor: '#ffb238',
        modalOverlayColor: 'rgba(30, 8, 24, 0.9)',
        modalOverlayBlur: 2,
        modalBorderRadius: 0,
        tooltipBg: '#ff6b35',
        tooltipTextColor: '#1a0612',
        tooltipRadius: 0,
        tableHeaderBg: 'rgba(255, 178, 56, 0.1)',
        tableRowHoverBg: 'rgba(255, 107, 53, 0.1)',
        tableCellPadding: 16,
        tableBorderColor: '#ff6b35',
        headingFont: "'JetBrains Mono', monospace",
        bodyFont: "'Inter', sans-serif",
        monoFont: "'JetBrains Mono', monospace",
        textColorMaster: '#fff1e6',
        textColorSecondary: '#ffc966',
        textColorMuted: '#e8b8a0',
        h1Size: 64,
        h1Weight: '900',
        h1LineHeight: 1,
        h1LetterSpacing: 4,
        h2Size: 36,
        h2Weight: '900',
        h2LineHeight: 1.2,
        bodyLineHeight: 1.8,
        bodyWeight: '400',
        headingTransform: 'uppercase',
        textSmoothing: false,
        textGlowIntensity: 1,
        btnBorderRadius: 0,
        btnRadiusTL: 16,
        btnRadiusTR: 0,
        btnRadiusBL: 0,
        btnRadiusBR: 16,
        btnHoverScale: 1.05,
        btnActiveScale: 0.95,
        btnPrimaryBg: '#ff6b35',
        btnPrimaryText: '#1a0612',
        btnSecondaryBg: 'rgba(255, 178, 56, 0.1)',
        btnGhostHoverBg: 'rgba(255, 107, 53, 0.2)',
        btnStyleType: 'borderline',
        btnNeonGlowColor: 'rgba(255, 107, 53, 0.7)',
        btnNeonPulseSpeed: 0.5,
        btnBackdropBlur: 0,
        inputBorderRadius: 0,
        inputBg: '#4a1942',
        inputTextColor: '#fff1e6',
        switchTrackActiveBg: '#ff6b35',
        switchThumbBg: '#ffb238',
        checkboxActiveColor: '#ff6b35',
        switchStyleType: 'tactile',
        switchBackdropBlur: 0,
        switchPulseColor: '#ffb238',
        colorPalette: 'default',
        primaryColor: '#ff6b35',
        secondaryColor: '#ffb238',
        tertiaryColor: '#7209b7',
        accentColor: '#ff3d81',
        surfaceColor: '#5c1f4a',
        textureColor: '#ff6b35',
        titleColor: '#ffb238',
        colorDepth: 1,
        colorVariation: 1,
        colorBgBody: '#6b2456',
        colorBgLayer1: '#551c46',
        colorBgLayer2: '#441639',
        colorBgModal: 'rgba(30, 8, 24, 0.95)',
        chartColorPalette: '#ff6b35',
        chartGridOpacity: 0.2,
        chartTooltipBg: '#4a1942',
        chartType: 'bar',
        chartShowGrid: true,
        chartThickness: 4,
        chartSmoothing: false,
        animInstant: 50,
        animFast: 100,
        animNormal: 200,
        animSlow: 400,
        easeMain: 'linear',
        easeOut: 'linear',
        animEnabled: true,
        bgGradientMode: 'linear',
        bgGradientAngle: 180,
        surfaceMaterial: 'sleek',
        surfaceIntensity: 1,
        borderType: 'solid',
        systemTone: 'dark',
        texture: 'grid',
        textureOpacity: 0.25,
        atmosphereNoiseOpacity: 0.1,
        noiseIntensity: 0.1,
        bgNoiseDensity: 0.05,
        bgNoiseAnimation: 1,
        glassBlur: 0,
        glassOpacity: 1,
        glassSpecularity: 0,
        glassRoughness: 1,
        glassSaturation: 1,
        shadowIntensity: 1,
        layeredShadows: 0,
        shadowOrientation: 'bottom-right',
        shadowColorMode: 'colored',
        shadowAmbientAlpha: 0.6,
        shadowProjectionBlur: 0,
        shadowProjectionAlpha: 1,
        securityShieldGlow: 20,
        securityPulseSpeed: 1,
        vignetteOpacity: 0.5,
        vignetteSoftness: 100,
        globalSaturation: 1.6,
        globalContrast: 1.3,
        contrastCurve: 1.2,
        chatBubbleRadius: 0,
        chatUserBg: '#ff6b35',
        chatBubbleStyle: 'solid',
        chatAnimationSpeed: 0.1,
        statusSuccessColor: '#10b981',
        statusErrorColor: '#ef4444',
        statusWarningColor: '#f59e0b',
        statusInfoColor: '#3b82f6',
        badgeRadius: 0,
        focusRingWidth: 4,
        reducedMotion: true,
        zIndexModal: 2000,
        zIndexToast: 2000,
        aiPanelBg: '#4a1942',
        aiGlowColor: '#ff6b35',
        flowNodeRadius: 0,
        flowGridStyle: 'lines',
        motionEaseMain: 'linear',
        motionEaseOut: 'linear',
        motionEaseIn: 'linear',
        motionDurationInstant: 0.1,
        motionDurationFast: 0.1,
        motionDurationNormal: 0.2,
        motionDurationSlow: 0.4,
        motionStaggerDelay: 0.1,
        scrollWidth: 12,
        scrollRadius: 0,
        scrollTrackOpacity: 0.2,
        scrollThumbColor: '#ff6b35',
        scrollThumbOpacity: 1,
        scrollThumbHoverOpacity: 1,
        scrollPadding: 0,
        zIndexBase: 1,
        zIndexSidebar: 500,
        zIndexTooltip: 9000,
        layerBackdropBlur: 0,
        layerBackdropOpacity: 0.9,
        layerElevationFactor: 2,
        matrixGap: 24,
        matrixRadius: 0,
        matrixItemBg: '#4a1942',
        matrixBorderColor: '#ff6b35',
        matrixSearchBg: '#3d1734',
        matrixBlur: 0,
        enabledLanguages: ['pt', 'en', 'es', 'fr', 'de', 'it'],
    },
    contraparte: {
        mode: 'light',
        bgBaseColor: '#fff5ec',
        colorBgBody: '#fff5ec',
        colorBgLayer1: '#ffffff',
        colorBgLayer2: '#ffeee0',
        sidebarColor: '#ffffff',
        sidebarHoverColor: 'rgba(201, 79, 31, 0.08)',
        sidebarActiveColor: 'rgba(201, 79, 31, 0.14)',
        topbarColor: '#ffffff',
        topbarHoverColor: 'rgba(201, 79, 31, 0.08)',
        topbarActiveColor: 'rgba(201, 79, 31, 0.14)',
        topbarTitleColor: '#5c1f4a',
        cardBackgroundColor: '#ffffff',
        cardBorderColor: '#f0c9a8',
        cardHeaderBg: '#fff0e4',
        cardHeaderBorder: '#f0c9a8',
        cardFooterBg: '#fff0e4',
        cardFooterBorder: '#f0c9a8',
        cardTitleColor: '#5c1f4a',
        cardTitleIconGlow: 'rgba(201, 79, 31, 0.2)',
        cardActionBtnPrimaryBg: '#c94f1f',
        cardActionBtnHoverBg: '#a83f16',
        cardActionBtnText: '#ffffff',
        cardSearchBgFocus: '#fff0e4',
        cardSearchPlaceholderColor: '#8a6b7d',
        cardSearchTextFocusColor: '#3d1730',
        modalOverlayColor: 'rgba(255, 245, 236, 0.85)',
        colorBgModal: '#fff5ec',
        tooltipBg: '#3d1730',
        tooltipTextColor: '#fff5ec',
        tableHeaderBg: '#fff0e4',
        tableRowHoverBg: '#ffe6d3',
        tableBorderColor: '#f0c9a8',
        textColorMaster: '#3d1730',
        textColorSecondary: '#6b2456',
        textColorMuted: '#764f65',
        btnPrimaryBg: '#c94f1f',
        btnPrimaryText: '#ffffff',
        btnSecondaryBg: '#fff0e4',
        btnGhostHoverBg: '#ffe6d3',
        inputBg: '#ffffff',
        inputBorderColor: '#f0c9a8',
        inputFocusBorderColor: '#c94f1f',
        inputTextColor: '#3d1730',
        switchThumbBg: '#ffffff',
        surfaceColor: '#fff0e4',
        textureColor: '#f0c9a8',
        titleColor: '#5c1f4a',
        chartTooltipBg: '#fff0e4',
        scrollThumbColor: '#f0c9a8',
        aiPanelBg: '#ffffff',
        matrixItemBg: '#fff0e4',
        matrixBorderColor: '#f0c9a8',
        matrixSearchBg: '#ffffff',
        navItemActiveColor: '#a83f16',
        navActiveMarkerColor: '#a83f16',
    }
};
