const fs = require('fs');
const path = require('path');

const THEMES_DIR = path.join(__dirname, '..', 'src', 'core', 'Design', 'presets', 'themes');

// O template mestre baseado na especificação do ThemePreset e MASTER_DESIGN_MAP
const masterTemplate = {
    matrixGap: 8,
    matrixRadius: 8,
    matrixItemBg: 'rgba(255,255,255,1)',
    matrixBorderColor: 'rgba(0,0,0,0.1)',
    matrixSearchBg: 'rgba(255,255,255,1)',
    matrixBlur: 0,
    animInstant: 100,
    animFast: 200,
    animNormal: 300,
    animSlow: 500,
    easeMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
    easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
    animEnabled: true,
    pageTransitionType: 'fade',
    cardHoverStyle: 'lift',
    colorBgBody: '#f8fafc',
    colorBgLayer1: '#ffffff',
    colorBgLayer2: '#f1f5f9',
    bgBaseColor: '#ffffff',
    bgGradientMode: 'none',
    bgGradientAngle: 0,
    surfaceMaterial: 'solid',
    surfaceIntensity: 1,
    borderType: 'solid',
    systemTone: 'neutral',
    atmosphereNoiseOpacity: 0,
    noiseIntensity: 0,
    bgNoiseDensity: 0,
    bgNoiseAnimation: 0,
    glassBlur: 0,
    glassOpacity: 1,
    glassRoughness: 1,
    glassSaturation: 1,
    shadowIntensity: 0,
    layeredShadows: 0,
    shadowColorMode: 'monochrome',
    shadowAmbientAlpha: 0.05,
    shadowProjectionBlur: 0,
    shadowProjectionAlpha: 0.1,
    securityShieldGlow: 0,
    securityPulseSpeed: 0,
    vignetteOpacity: 0,
    vignetteSoftness: 0,
    globalSaturation: 1,
    globalContrast: 1,
    contrastCurve: 1,
    identityAlignment: 'left',
    identityPadding: 16,
    identityFontFamily: 'Inter',
    identityFontWeight: 600,
    identityTracking: 0,
    identityRedirectUrl: '/',
    identityHoverEffect: 'opacity',
    btnBorderRadius: 0,
    btnRadiusTL: 8,
    btnRadiusTR: 8,
    btnRadiusBL: 8,
    btnRadiusBR: 8,
    btnHoverScale: 1.02,
    btnActiveScale: 0.98,
    btnPrimaryBg: '#0f172a',
    btnPrimaryText: '#FFFFFF',
    btnSecondaryBg: '#FFFFFF',
    btnGhostHoverBg: '#E0E0E0',
    btnStyleType: 'solid',
    btnNeonGlowColor: 'transparent',
    btnNeonPulseSpeed: 0,
    btnBackdropBlur: 0,
    cardActionBtnPrimaryBg: '#0f172a',
    cardActionBtnHoverBg: '#2563eb',
    cardActionBtnText: '#FFFFFF',
    cardActionBtnBorderRadius: 8,
    cardActionBtnPadding: 12,
    cardActionClickScale: 0.95,
    cardSearchBgFocus: '#ffffff',
    cardSearchBorderBeamActive: false,
    cardSearchPlaceholderColor: '#94a3b8',
    cardSearchTextFocusColor: '#0f172a',
    cardTitleFontSize: 18,
    cardTitleColor: '#0f172a',
    cardTitleFontWeight: '600',
    cardTitleLetterSpacing: 0,
    cardTitleIconGlow: 'transparent',
    cardBorderRadius: 0,
    cardRadiusTL: 16,
    cardRadiusTR: 16,
    cardRadiusBL: 16,
    cardRadiusBR: 16,
    cardGeometricCut: 0,
    cardBackgroundColor: '#FFFFFF',
    cardBackdropBlur: 0,
    cardSurfaceOpacity: 1,
    cardBorderWidth: 1,
    cardBorderColor: '#e2e8f0',
    cardBorderOpacity: 1,
    cardBorderTop: 1,
    cardBorderBottom: 1,
    cardBorderLeft: 1,
    cardBorderRight: 1,
    cardInnerGlowColor: 'transparent',
    cardInnerGlowWidth: 0,
    cardTextureType: 'none',
    cardTextureOpacity: 0,
    cardHeaderBg: 'transparent',
    cardHeaderBorder: '#e2e8f0',
    cardHeaderPadding: 16,
    cardFooterBg: '#f8fafc',
    cardFooterBorder: '#e2e8f0',
    cardShadowSpread: 0,
    cardGlowColor: 'transparent',
    cardGlowIntensity: 0,
    cardHoverTranslate: 0,
    cardHoverGlowIncrease: 0,
    cardSpotlightOpacity: 0,
    cardPaddingMd: 24,
    cardVariant: 'solid',
    imageCardOverlayOpacity: 0.2,
    imageCardHoverZoom: 1.05,
    chatBubbleRadius: 16,
    chatUserBg: '#3b82f6',
    chatBubbleStyle: 'solid',
    chatAnimationSpeed: 0.2,
    colorPalette: 'default',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    tertiaryColor: '#8b5cf6',
    accentColor: '#94a3b8',
    surfaceColor: '#FFFFFF',
    textureColor: '#e2e8f0',
    titleColor: '#0f172a',
    colorDepth: 1,
    colorVariation: 1,
    colorBgModal: 'rgba(0,0,0,0.5)',
    chartColorPalette: '#3b82f6',
    chartGridOpacity: 0.1,
    chartTooltipBg: '#ffffff',
    chartType: 'line',
    chartShowGrid: true,
    chartThickness: 2,
    chartSmoothing: true,
    focusRingWidth: 2,
    reducedMotion: false,
    zIndexModal: 1000,
    zIndexToast: 2000,
    mode: 'light',
    navigationStyle: 'topbar',
    bodySize: '16px',
    inputBorderRadius: 0,
    inputBg: '#FFFFFF',
    inputBorderColor: '#cbd5e1',
    inputFocusBorderColor: '#3b82f6',
    inputTextColor: '#0f172a',
    inputRadius: 8,
    zIndexBase: 1,
    zIndexSidebar: 50,
    zIndexTooltip: 100,
    layerBackdropBlur: 0,
    layerBackdropOpacity: 0.5,
    layerElevationFactor: 1,
    globalBackgroundImageUrl: '',
    globalBackgroundBlur: 0,
    globalBackgroundBlendMode: 'normal',
    globalBackgroundOpacity: 1,
    motionEaseMain: 'cubic-bezier(0.4, 0, 0.2, 1)',
    motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',
    motionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
    motionDurationInstant: 0.1,
    motionDurationFast: 0.2,
    motionDurationNormal: 0.3,
    motionDurationSlow: 0.5,
    motionStaggerDelay: 0.05,
    isNavHidden: false,
    sidebarWidth: 260,
    sidebarMinWidth: 200,
    sidebarMaxWidth: 320,
    sidebarColor: '#ffffff',
    sidebarHoverColor: '#f1f5f9',
    sidebarActiveColor: '#e2e8f0',
    sidebarNoiseOpacity: 0,
    topbarHeight: 64,
    topbarColor: '#ffffff',
    topbarHoverColor: '#f1f5f9',
    topbarActiveColor: '#e2e8f0',
    topbarNoiseOpacity: 0,
    topbarTitleColor: '#0f172a',
    tabGap: 8,
    tabSectionMargin: 16,
    navItemActiveColor: '#3b82f6',
    navActiveMarkerColor: '#3b82f6',
    navActiveMarkerGlow: 0,
    sidebarBlur: 0,
    sidebarShadow: '1px 0 0 #e2e8f0',
    searchPositionTopbar: 'center',
    searchPositionSidebar: 'none',
    modalOverlayColor: 'rgba(0,0,0,0.5)',
    modalOverlayBlur: 4,
    modalBorderRadius: 16,
    tooltipBg: '#1e293b',
    tooltipRadius: 4,
    scrollWidth: 6,
    scrollRadius: 10,
    scrollTrackOpacity: 0.1,
    scrollThumbColor: '#cbd5e1',
    scrollThumbOpacity: 1,
    scrollThumbHoverOpacity: 1,
    scrollPadding: 2,
    aiPanelBg: '#ffffff',
    aiGlowColor: '#3b82f6',
    flowNodeRadius: 8,
    flowGridStyle: 'dots',
    statusSuccessColor: '#10b981',
    statusErrorColor: '#ef4444',
    statusWarningColor: '#f59e0b',
    statusInfoColor: '#3b82f6',
    badgeRadius: 0,
    switchTrackActiveBg: '#3b82f6',
    switchThumbBg: '#ffffff',
    checkboxActiveColor: '#3b82f6',
    switchStyleType: 'solid',
    switchBackdropBlur: 0,
    switchPulseColor: 'rgba(59, 130, 246, 0.5)',
    layout: 'grid',
    layoutDensity: 'comfortable',
    maxContentWidth: '1440px',
    layoutPadding: 24,
    isSplitViewEnabled: false,
    isAutoHideEnabled: false,
    borderRadius: 8,
    borderRadiusSm: 4,
    borderRadiusMd: 8,
    borderRadiusLg: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    layoutGap: 24,
    layoutGapSm: 12,
    layoutGapMd: 24,
    layoutGapLg: 48,
    iconFamily: 'lucide',
    iconWeight: 'regular',
    iconStrokeWidth: 2,
    scrollbarWidth: 6,
    scrollbarThumbColor: '#cbd5e1',
    industrialRegistry: false,
    tableHeaderBg: '#f8fafc',
    tableRowHoverBg: '#f1f5f9',
    tableCellPadding: 16,
    tableBorderColor: '#e2e8f0',
    headingFont: '"Inter", sans-serif',
    bodyFont: '"Inter", sans-serif',
    monoFont: '"Fira Code", monospace',
    textColorMaster: '#0f172a',
    textColorSecondary: '#475569',
    textColorMuted: '#94a3b8',
    h1Size: 36,
    h1Weight: '700',
    h1LineHeight: 1.2,
    h1LetterSpacing: -1,
    h2Size: 30,
    h2Weight: '600',
    h2LineHeight: 1.3,
    bodyLineHeight: 1.6,
    bodyWeight: '400',
    headingTransform: 'none',
    textSmoothing: true,
    textGlowIntensity: 0,
};

// As master configurations baseadas no novo design plan
const themes = [
    {
        id: 'minimalist-airy',
        name: 'Minimalist Airy',
        description: 'Luxo minimalista com branco absoluto, tipografia imponente e limpeza cirúrgica.',
        overrides: {
            colorBgBody: '#F9FAFB',
            colorBgLayer1: '#FFFFFF',
            colorBgLayer2: '#F3F4F6',
            bgBaseColor: '#FFFFFF',
            cardBackgroundColor: '#FFFFFF',
            surfaceColor: '#FFFFFF',
            primaryColor: '#111827',
            secondaryColor: '#4B5563',
            tertiaryColor: '#9CA3AF',
            accentColor: '#E5E7EB',
            btnPrimaryBg: '#111827',
            cardActionBtnPrimaryBg: '#111827',
            btnStyleType: 'solid',
            borderRadius: 9999, // Pilulas extremas para botões onde aplicável
            borderRadiusLg: 48, // Cartões com grande arredondamento
            btnRadiusTL: 9999, btnRadiusTR: 9999, btnRadiusBL: 9999, btnRadiusBR: 9999,
            cardRadiusTL: 32, cardRadiusTR: 32, cardRadiusBL: 32, cardRadiusBR: 32,
            borderWidth: 0,
            cardBorderWidth: 0,
            shadowProjectionBlur: 60,
            shadowAmbientAlpha: 0.02,
            shadowIntensity: 1, // Ativa as sombras
            layeredShadows: 1,
            headingFont: '"Inter", sans-serif',
            bodyFont: '"Inter", sans-serif',
            h1Weight: '800',
            layoutDensity: 'spacious',
            layoutPadding: 48,
            layoutGap: 48,
            cardHoverStyle: 'lift',
            cardHoverTranslate: -8,
            topbarColor: '#FFFFFF',
            sidebarColor: '#F9FAFB',
        }
    },
    {
        id: 'data-terminal',
        name: 'Data Terminal',
        description: 'Tela preta estilo terminal, bordas rígidas e detalhes em ciano/neon para alta densidade de dados.',
        overrides: {
            mode: 'dark',
            colorBgBody: '#000000',
            colorBgLayer1: '#09090b',
            colorBgLayer2: '#18181b',
            bgBaseColor: '#000000',
            cardBackgroundColor: '#09090b',
            surfaceColor: '#000000',
            primaryColor: '#06b6d4', // Ciano neon
            secondaryColor: '#a1a1aa',
            tertiaryColor: '#10b981',
            accentColor: '#3f3f46',
            btnPrimaryBg: 'transparent',
            btnPrimaryText: '#06b6d4',
            btnStyleType: 'outline',
            btnBorderRadius: 0,
            btnRadiusTL: 0, btnRadiusTR: 0, btnRadiusBL: 0, btnRadiusBR: 0,
            cardRadiusTL: 0, cardRadiusTR: 0, cardRadiusBL: 0, cardRadiusBR: 0,
            borderRadius: 0, borderRadiusLg: 0,
            borderWidth: 1,
            cardBorderWidth: 1,
            cardBorderColor: '#27272a',
            shadowProjectionBlur: 0,
            shadowAmbientAlpha: 0,
            shadowIntensity: 0,
            layeredShadows: 0,
            headingFont: '"Fira Code", monospace',
            bodyFont: '"Fira Code", monospace',
            h1Size: 28,
            layoutDensity: 'compact',
            layoutPadding: 16,
            layoutGap: 16,
            cardHoverStyle: 'glow',
            cardGlowColor: 'rgba(6, 182, 212, 0.2)',
            cardHoverGlowIncrease: 0.5,
            textColorMaster: '#f4f4f5',
            topbarColor: '#09090b',
            sidebarColor: '#000000',
            inputBg: '#09090b',
            inputBorderColor: '#27272a',
            inputFocusBorderColor: '#06b6d4',
            inputTextColor: '#06b6d4',
            inputRadius: 0
        }
    },
    {
        id: 'neumorphic-mobile',
        name: 'Neumorphic Mobile',
        description: 'Design de relevo e rebaixos (Soft UI) criando superfícies como silicone ou borracha contínua.',
        overrides: {
            colorBgBody: '#e0e5ec',
            colorBgLayer1: '#e0e5ec',
            colorBgLayer2: '#e0e5ec',
            bgBaseColor: '#e0e5ec',
            cardBackgroundColor: '#e0e5ec',
            surfaceColor: '#e0e5ec',
            primaryColor: '#5c6b73',
            secondaryColor: '#93a1a1',
            tertiaryColor: '#ffb3c6', // Detalhes em rosa pastel
            btnPrimaryBg: '#e0e5ec',
            btnPrimaryText: '#5c6b73',
            btnStyleType: 'neumorphic',
            cardVariant: 'neumorphic',
            borderRadius: 24,
            borderRadiusLg: 32,
            btnRadiusTL: 24, btnRadiusTR: 24, btnRadiusBL: 24, btnRadiusBR: 24,
            cardRadiusTL: 32, cardRadiusTR: 32, cardRadiusBL: 32, cardRadiusBR: 32,
            borderWidth: 0,
            cardBorderWidth: 0,
            shadowIntensity: 1,
            shadowProjectionBlur: 20, // Difusão neumorfica
            shadowAmbientAlpha: 0.1,
            headingFont: '"Outfit", sans-serif',
            bodyFont: '"Outfit", sans-serif',
            textColorMaster: '#3d4b52',
            topbarColor: '#e0e5ec',
            sidebarColor: '#e0e5ec',
            inputBg: '#e0e5ec', // Input rebaixado é tratado pelo neumorphic inner shadow (via css variables map)
            inputBorderColor: 'transparent',
            inputFocusBorderColor: '#ffb3c6',
            inputRadius: 24
        }
    },
    {
        id: 'industrial-dashboard',
        name: 'Industrial Dashboard',
        description: 'Painel rígido, metálico, com traços fortes de HUD e alertas em cores de construção técnica.',
        overrides: {
            mode: 'dark',
            colorBgBody: '#18181b', // Asfalto
            colorBgLayer1: '#27272a', // Painel Metálico escuro
            colorBgLayer2: '#3f3f46',
            bgBaseColor: '#18181b',
            cardBackgroundColor: '#27272a',
            surfaceColor: '#27272a',
            primaryColor: '#eab308', // Amarelo alerta/caterpillar
            secondaryColor: '#f97316', // Laranja warning
            tertiaryColor: '#64748b',
            btnPrimaryBg: '#eab308',
            btnPrimaryText: '#18181b', // Preto no amarelo
            btnStyleType: 'solid',
            borderRadius: 4,
            borderRadiusLg: 8,
            btnRadiusTL: 4, btnRadiusTR: 4, btnRadiusBL: 4, btnRadiusBR: 4,
            cardRadiusTL: 8, cardRadiusTR: 8, cardRadiusBL: 8, cardRadiusBR: 8,
            borderWidth: 2,
            cardBorderWidth: 2,
            cardBorderColor: '#3f3f46',
            shadowIntensity: 0.5,
            shadowProjectionBlur: 4,
            shadowAmbientAlpha: 0.5,
            headingFont: '"Inter", sans-serif',
            bodyFont: '"Inter", sans-serif',
            h1Weight: '900', // Pesado
            textColorMaster: '#f4f4f5',
            topbarColor: '#27272a',
            sidebarColor: '#18181b',
            inputBg: '#18181b',
            inputBorderColor: '#3f3f46',
            inputFocusBorderColor: '#eab308',
            inputTextColor: '#f4f4f5',
            inputRadius: 4,
            industrialRegistry: true
        }
    },
    {
        id: 'asymmetric-editorial',
        name: 'Asymmetric Editorial',
        description: 'Revista de moda avant-garde, preto e branco puro de alto contraste, elementos grandes sem bordas delimitadoras.',
        overrides: {
            colorBgBody: '#fdfbf7', // Papel creme luxo
            colorBgLayer1: '#fdfbf7',
            colorBgLayer2: '#f3ece1',
            bgBaseColor: '#fdfbf7',
            cardBackgroundColor: 'transparent', // Cartões flutuam sobre o grid
            surfaceColor: '#fdfbf7',
            primaryColor: '#000000',
            secondaryColor: '#333333',
            tertiaryColor: '#888888',
            btnPrimaryBg: '#000000',
            btnPrimaryText: '#ffffff',
            btnStyleType: 'outline',
            btnBorderRadius: 0,
            borderRadius: 0,
            borderRadiusLg: 0,
            btnRadiusTL: 0, btnRadiusTR: 0, btnRadiusBL: 0, btnRadiusBR: 0,
            cardRadiusTL: 0, cardRadiusTR: 0, cardRadiusBL: 0, cardRadiusBR: 0,
            borderWidth: 1,
            cardBorderWidth: 1, // Brutalismo
            cardBorderColor: '#000000',
            shadowIntensity: 1,
            shadowProjectionBlur: 0, // Sombra dura
            shadowAmbientAlpha: 1,
            cardShadowSpread: 8, // Deslocamento duro e brutalista
            headingFont: '"Playfair Display", serif',
            bodyFont: '"Inter", sans-serif',
            h1Size: 64, // Enorme
            h1Weight: '900',
            h1LineHeight: 1.1,
            h1LetterSpacing: -2,
            layout: 'masonry',
            layoutGap: 80,
            layoutPadding: 64,
            textColorMaster: '#000000',
            topbarColor: '#fdfbf7',
            sidebarColor: '#fdfbf7',
            inputBg: 'transparent',
            inputBorderColor: '#000000',
            inputFocusBorderColor: '#000000',
            inputTextColor: '#000000',
            inputRadius: 0,
            textSmoothing: true
        }
    }
];

themes.forEach(theme => {
    // Mescla o template com os overrides específicos
    const finalDesign = { ...masterTemplate, ...theme.overrides };

    // Converte o objeto design para string com formatação
    const designStr = Object.entries(finalDesign)
        .map(([key, value]) => {
            if (typeof value === 'string') {
                return `        ${key}: '${value}',`;
            }
            return `        ${key}: ${value},`;
        })
        .join('\n');

    const fileContent = `import { ThemePreset } from '../../catalog/ThemePreset';

export const ${theme.id.replace(/-([a-z])/g, (g) => g[1].toUpperCase())}: ThemePreset = {
    id: '${theme.id}',
    name: '${theme.name}',
    description: '${theme.description}',
    design: {
${designStr}
    }
};
`;

    const filePath = path.join(THEMES_DIR, `${theme.id}.ts`);
    fs.writeFileSync(filePath, fileContent, 'utf-8');
    console.log(`Generated ${theme.id}.ts`);
});
