import { z } from 'zod';

export const LLMMessageSchema = z.object({
    role: z.string().describe("Role of the message author: 'system', 'user', or 'assistant'"),
    content: z.string().describe("Text content of the message")
});
export type LLMMessage = z.infer<typeof LLMMessageSchema>;

export const CapabilitiesConfigSchema = z.object({
    input_modalities: z.array(z.string()).default(["text"]).describe("Supported input modalities like 'text', 'image_url'"),
    output_format: z.string().default("text").describe("Output format like 'text' or 'json_object'")
});
export type CapabilitiesConfig = z.infer<typeof CapabilitiesConfigSchema>;

export const AgentConfigModelSchema = z.object({
    model: z.string().describe("The name of the LLM model to use"),
    temperature: z.number().default(0.7).describe("Sampling temperature"),
    max_tokens: z.number().default(1000).describe("Max tokens in the output response"),
    provider: z.string().describe("Provider name: 'groq' or 'openrouter'"),
    system_prompt_override: z.string().optional().describe("Optional system prompt override"),
    features: z.object({
        rag: z.boolean().default(false)
    }).optional(),
    capabilities: CapabilitiesConfigSchema.optional()
});
export type AgentConfigModel = z.infer<typeof AgentConfigModelSchema>;

export const MessagePartSchema = z.object({
    type: z.string().describe("Type of content: 'text', 'image_url', etc."),
    content: z.string().optional().describe("Text content if type is text"),
    url: z.string().optional().describe("URL content if type is image_url")
});
export type MessagePart = z.infer<typeof MessagePartSchema>;

export const ChatRequestSchema = z.object({
    agentId: z.string().optional().describe("The ID of the target agent"),
    payload: z.array(MessagePartSchema).describe("Multimodal user message payload"),
    sessionId: z.string().describe("Session identifier for thread history preservation"),
    metadata: z.record(z.string(), z.any()).optional().describe("Optional anonymous telemetry metadata collected by client/server")
});
export type ChatRequest = z.infer<typeof ChatRequestSchema>;

export const TriggerActionSchema = z.object({
    type: z.string().describe("The trigger action identifier, e.g., 'LEAD', 'APPOINTMENT', 'HANDOFF'"),
    data: z.record(z.string(), z.any()).default({}).describe("Metadata associated with the trigger action")
});
export type TriggerAction = z.infer<typeof TriggerActionSchema>;

export const ChatResponseSchema = z.object({
    text: z.string().describe("Clean response text generated by the agent"),
    actions: z.array(TriggerActionSchema).default([]).describe("Extracted trigger actions from the response"),
    agentId: z.string().describe("The ID of the agent that responded")
});
export type ChatResponse = z.infer<typeof ChatResponseSchema>;

export interface LLMConfig {
    temperature: number;
    max_tokens: number;
    provider: string;
    model: string;
    retries?: {
        enabled: boolean;
        max_attempts: number;
        initial_delay_ms: number;
    };
}

export interface RateLimitConfig {
    enabled: boolean;
    max_requests: number;
    window_seconds: number;
}

export interface PromptInjectionConfig {
    enabled: boolean;
    blocked_keywords: string[];
}

export interface SecurityConfig {
    api_auth?: {
        enabled: boolean;
    };
    cors?: {
        allowed_origins: string[];
    };
    rate_limit: RateLimitConfig;
    prompt_injection: PromptInjectionConfig;
}
