import { 
    AlertCircle as LucideAlertCircle, 
    Check as LucideCheck, 
    X as LucideX, 
    Menu as LucideMenu, 
    Search as LucideSearch, 
    Bell as LucideBell, 
    User as LucideUser,
    LogOut as LucideLogOut,
    Shield as LucideShield,
    Globe as LucideGlobe,
    ChevronDown as LucideChevronDown,
    ChevronLeft as LucideChevronLeft,
    ChevronRight as LucideChevronRight,
    Zap as LucideZap,
    LayoutDashboard as LucideLayoutDashboard,
    Save as LucideSave,
    Settings as LucideSettings,
    BarChart3 as LucideBarChart3,
    Layout as LucideLayout,
    FileText as LucideFileText,
    MessageSquare as LucideMessageSquare,
    History as LucideHistory,
    Network as LucideNetwork,
    Box as LucideBox,
    Type as LucideType,
    Lock as LucideLock,
    Layers as LucideLayers,
    Grid as LucideGrid,
    AlignLeft as LucideAlignLeft,
    LineChart as LucideLineChart
} from 'lucide-react';

import { 
    WarningCircle as PhosphorAlertCircle, 
    Check as PhosphorCheck, 
    X as PhosphorX, 
    List as PhosphorMenu, 
    MagnifyingGlass as PhosphorSearch, 
    Bell as PhosphorBell, 
    User as PhosphorUser,
    SignOut as PhosphorLogOut,
    Shield as PhosphorShield,
    Globe as PhosphorGlobe,
    CaretDown as PhosphorChevronDown,
    CaretLeft as PhosphorChevronLeft,
    CaretRight as PhosphorChevronRight,
    Lightning as PhosphorZap,
    SquaresFour as PhosphorLayoutDashboard,
    FloppyDisk as PhosphorSave,
    Gear as PhosphorSettings,
    ChartBar as PhosphorBarChart3,
    Layout as PhosphorLayout,
    FileText as PhosphorFileText,
    ChatCircle as PhosphorMessageSquare,
    ClockCounterClockwise as PhosphorHistory,
    ShareNetwork as PhosphorNetwork,
    Cube as PhosphorBox,
    TextT as PhosphorType,
    LockKey as PhosphorLock,
    Stack as PhosphorLayers,
    GridFour as PhosphorGrid,
    TextAlignLeft as PhosphorAlignLeft,
    ChartLineUp as PhosphorLineChart
} from '@phosphor-icons/react';

import { 
    IconAlertCircle as TablerAlertCircle, 
    IconCheck as TablerCheck, 
    IconX as TablerX, 
    IconMenu2 as TablerMenu, 
    IconSearch as TablerSearch, 
    IconBell as TablerBell, 
    IconUser as TablerUser,
    IconLogout as TablerLogOut,
    IconShield as TablerShield,
    IconWorld as TablerGlobe,
    IconChevronDown as TablerChevronDown,
    IconChevronLeft as TablerChevronLeft,
    IconChevronRight as TablerChevronRight,
    IconBolt as TablerZap,
    IconLayoutDashboard as TablerLayoutDashboard,
    IconDeviceFloppy as TablerSave,
    IconSettings as TablerSettings,
    IconChartBar as TablerBarChart3,
    IconLayout as TablerLayout,
    IconFileText as TablerFileText,
    IconMessage as TablerMessageSquare,
    IconHistory as TablerHistory,
    IconNetwork as TablerNetwork,
    IconBox as TablerBox,
    IconTypography as TablerType,
    IconLock as TablerLock,
    IconStack2 as TablerLayers,
    IconGridDots as TablerGrid,
    IconAlignLeft as TablerAlignLeft,
    IconChartLine as TablerLineChart
} from '@tabler/icons-react';

export type IconName = 
    | 'AlertCircle' | 'Check' | 'X' | 'Menu' | 'Search' | 'Bell' | 'User' 
    | 'LogOut' | 'Shield' | 'Globe' | 'ChevronDown' | 'ChevronLeft' 
    | 'ChevronRight' | 'Zap' | 'LayoutDashboard' | 'Save' | 'Settings'
    | 'BarChart3' | 'Layout' | 'FileText' | 'MessageSquare' | 'History'
    | 'Network' | 'Box' | 'Type' | 'Lock' | 'Layers' | 'Grid' | 'AlignLeft' | 'LineChart';

export const IconMap: Record<IconName, { lucide: any, phosphor: any, tabler: any }> = {
    AlertCircle: { lucide: LucideAlertCircle, phosphor: PhosphorAlertCircle, tabler: TablerAlertCircle },
    Check: { lucide: LucideCheck, phosphor: PhosphorCheck, tabler: TablerCheck },
    X: { lucide: LucideX, phosphor: PhosphorX, tabler: TablerX },
    Menu: { lucide: LucideMenu, phosphor: PhosphorMenu, tabler: TablerMenu },
    Search: { lucide: LucideSearch, phosphor: PhosphorSearch, tabler: TablerSearch },
    Bell: { lucide: LucideBell, phosphor: PhosphorBell, tabler: TablerBell },
    User: { lucide: LucideUser, phosphor: PhosphorUser, tabler: TablerUser },
    LogOut: { lucide: LucideLogOut, phosphor: PhosphorLogOut, tabler: TablerLogOut },
    Shield: { lucide: LucideShield, phosphor: PhosphorShield, tabler: TablerShield },
    Globe: { lucide: LucideGlobe, phosphor: PhosphorGlobe, tabler: TablerGlobe },
    ChevronDown: { lucide: LucideChevronDown, phosphor: PhosphorChevronDown, tabler: TablerChevronDown },
    ChevronLeft: { lucide: LucideChevronLeft, phosphor: PhosphorChevronLeft, tabler: TablerChevronLeft },
    ChevronRight: { lucide: LucideChevronRight, phosphor: PhosphorChevronRight, tabler: TablerChevronRight },
    Zap: { lucide: LucideZap, phosphor: PhosphorZap, tabler: TablerZap },
    LayoutDashboard: { lucide: LucideLayoutDashboard, phosphor: PhosphorLayoutDashboard, tabler: TablerLayoutDashboard },
    Save: { lucide: LucideSave, phosphor: PhosphorSave, tabler: TablerSave },
    Settings: { lucide: LucideSettings, phosphor: PhosphorSettings, tabler: TablerSettings },
    BarChart3: { lucide: LucideBarChart3, phosphor: PhosphorBarChart3, tabler: TablerBarChart3 },
    Layout: { lucide: LucideLayout, phosphor: PhosphorLayout, tabler: TablerLayout },
    FileText: { lucide: LucideFileText, phosphor: PhosphorFileText, tabler: TablerFileText },
    MessageSquare: { lucide: LucideMessageSquare, phosphor: PhosphorMessageSquare, tabler: TablerMessageSquare },
    History: { lucide: LucideHistory, phosphor: PhosphorHistory, tabler: TablerHistory },
    Network: { lucide: LucideNetwork, phosphor: PhosphorNetwork, tabler: TablerNetwork },
    Box: { lucide: LucideBox, phosphor: PhosphorBox, tabler: TablerBox },
    Type: { lucide: LucideType, phosphor: PhosphorType, tabler: TablerType },
    Lock: { lucide: LucideLock, phosphor: PhosphorLock, tabler: TablerLock },
    Layers: { lucide: LucideLayers, phosphor: PhosphorLayers, tabler: TablerLayers },
    Grid: { lucide: LucideGrid, phosphor: PhosphorGrid, tabler: TablerGrid },
    AlignLeft: { lucide: LucideAlignLeft, phosphor: PhosphorAlignLeft, tabler: TablerAlignLeft },
    LineChart: { lucide: LucideLineChart, phosphor: PhosphorLineChart, tabler: TablerLineChart },
};
